import type {
  Fact,
  Source,
  TechnologyCategory,
  TechnologyComparison,
  TechnologyFamily,
  TimelineEvent,
  TimelineLane,
} from "./types";

const ACCESSED_AT = "2026-07-23";

interface DeepSpeedMethod {
  id: string;
  date: string;
  title: string;
  tutorialSlug: string;
  tutorialFile: string;
  category: TechnologyCategory;
  family: TechnologyFamily;
  summary: string;
  situation: string;
  target: string;
  action: string;
  result: string;
  mechanism: string;
  bestFor: string;
  experiment: string;
  computeMemory: string;
  parallelism: string;
  limitations: string;
  availability: string;
  tags: string[];
  score?: string;
  paper?: { id: string; title: string; url: string; publisher: string };
}

function source(
  id: string,
  title: string,
  publisher: string,
  url: string,
  type: Source["type"],
): Source {
  return { id, title, publisher, url, type, accessedAt: ACCESSED_AT };
}

function disclosedFact(label: string, value: string, sourceIds: string[]): Fact {
  return { label, value, sourceIds, status: "已披露" };
}

function deepSpeedEvent(input: DeepSpeedMethod): TimelineEvent {
  const sources = [
    source(
      `${input.id}-tutorial`,
      `${input.title} Tutorial`,
      "DeepSpeed",
      `https://www.deepspeed.ai/tutorials/${input.tutorialSlug}/`,
      "官方博客",
    ),
    source(
      `${input.id}-history`,
      `${input.tutorialFile} commit history`,
      "deepspeedai/DeepSpeed",
      `https://github.com/deepspeedai/DeepSpeed/commits/master/docs/_tutorials/${input.tutorialFile}`,
      "代码仓",
    ),
    ...(input.paper
      ? [source(input.paper.id, input.paper.title, input.paper.publisher, input.paper.url, "论文")]
      : []),
  ];
  const sourceIds = sources.map((item) => item.id);
  const comparison: TechnologyComparison = {
    category: input.category,
    family: input.family,
    mechanism: input.mechanism,
    bestFor: input.bestFor,
    experiment: input.experiment,
    result: input.result,
    computeMemory: input.computeMemory,
    parallelism: input.parallelism,
    limitations: input.limitations,
    availability: input.availability,
  };

  return {
    id: input.id,
    date: input.date,
    title: input.title,
    organization: "DeepSpeed / Microsoft",
    eyebrow: "官方教程 + Git 历史",
    summary: input.summary,
    confidence: "高",
    score: input.score,
    tags: [...input.tags, input.category, input.family, "DeepSpeed", "STAR"],
    tier: "baseline",
    eventKind: "technology",
    star: {
      situation: input.situation,
      target: input.target,
      action: input.action,
      result: input.result,
    },
    comparison,
    revisionNotes: [
      `事件日期采用官方教程文件 ${input.tutorialFile} 在 DeepSpeed 仓库首次出现的提交日期；网页底部 Updated 是站点构建时间，不作为发布日期。`,
    ],
    facts: [
      disclosedFact("Situation / 动机", input.situation, sourceIds),
      disclosedFact("Target / 目标", input.target, sourceIds),
      disclosedFact("Action / 实验流程", input.action, sourceIds),
      disclosedFact("Result / 结果", input.result, sourceIds),
      disclosedFact("核心机制", input.mechanism, sourceIds),
      disclosedFact("适用场景", input.bestFor, sourceIds),
      disclosedFact("实验口径", input.experiment, sourceIds),
      disclosedFact("计算 / 显存", input.computeMemory, sourceIds),
      disclosedFact("并行维度", input.parallelism, sourceIds),
      disclosedFact("局限 / 适用边界", input.limitations, sourceIds),
      disclosedFact("代码 / 可用性", input.availability, sourceIds),
    ],
    sources,
  };
}

const zeroOffload = deepSpeedEvent({
  id: "tech-deepspeed-zero-offload",
  date: "2020-09-10",
  title: "ZeRO-Offload",
  tutorialSlug: "zero-offload",
  tutorialFile: "zero-offload.md",
  category: "并行方案",
  family: "并行系统",
  summary: "把优化器状态与优化器计算迁到 CPU，同时让 GPU 继续承担高吞吐前向、反向与参数更新所需的数据交换。",
  situation: "ZeRO 分片仍受 GPU 总显存约束，尤其 Adam 的 FP32 状态与更新计算占用显著。",
  target: "用 CPU 内存扩展单机可训练模型规模，并尽量保持 GPU 计算吞吐。",
  action: "把 optimizer state 和 optimizer step 放到 CPU，使用 pinned memory、CPU Adam 与分区参数/梯度的数据移动连接 GPU 训练。",
  result: "论文和教程证明单 GPU 也能训练十亿级以上模型；收益依赖 CPU、PCIe、NUMA 与计算通信重叠。",
  mechanism: "GPU 计算 + CPU optimizer/offload + 分块传输和重叠。",
  bestFor: "GPU 显存不足、CPU 内存充足且 PCIe/NUMA 可调优的训练。",
  experiment: "ZeRO-Offload 论文与 DeepSpeed 官方配置路径；不同硬件结果不可直接外推。",
  computeMemory: "降低 GPU optimizer-state 占用，但把容量和带宽压力转移到 host RAM 与 PCIe。",
  parallelism: "ZeRO data parallel，可与 TP/PP 组合。",
  limitations: "CPU 算力、内存带宽和 PCIe 暴露会成为瓶颈；不是免费显存。",
  availability: "DeepSpeed `zero_optimization.offload_optimizer` 配置可用。",
  tags: ["ZeRO-Offload", "CPU Offload", "Adam"],
  paper: {
    id: "zero-offload-paper",
    title: "ZeRO-Offload: Democratizing Billion-Scale Model Training",
    publisher: "USENIX ATC",
    url: "https://arxiv.org/abs/2101.06840",
  },
});

const zeroPlusPlus = deepSpeedEvent({
  id: "tech-deepspeed-zero-plus-plus",
  date: "2023-06-23",
  title: "ZeRO++",
  tutorialSlug: "zeropp",
  tutorialFile: "zeropp.md",
  category: "并行方案",
  family: "并行系统",
  summary: "围绕 ZeRO-3 的跨节点通信加入权重量化、分层分区与梯度量化，降低低带宽集群上的通信压力。",
  situation: "ZeRO-3 在跨节点网络较慢时，参数 all-gather 与梯度通信会压过计算。",
  target: "在保持 ZeRO 显存优势的同时显著降低跨节点通信量。",
  action: "组合量化权重通信、节点内次级参数分区与量化梯度通信，并在 DeepSpeed config 中分别启用。",
  result: "官方论文报告通信量最高降低 4×、吞吐最高提升 2.16×；该上限只适用于论文网络与模型口径。",
  mechanism: "qwZ + hpZ + qgZ：权重、分层参数副本与梯度三条通信路径分别优化。",
  bestFor: "多节点、跨节点带宽明显弱于节点内互联的 ZeRO-3 训练。",
  experiment: "不同网络带宽和模型规模下对比 ZeRO-3；不能把最高倍数套到 NVLink 单节点。",
  computeMemory: "以节点内次级副本和量化 buffer 换跨节点通信下降。",
  parallelism: "ZeRO-3 data parallel 的分层通信优化。",
  limitations: "需要额外显存、量化 kernel 与拓扑感知；并非所有网络都获益。",
  availability: "DeepSpeed ZeRO++ 配置公开。",
  tags: ["ZeRO++", "Quantized Communication", "Hierarchical Partition"],
  score: "up to 4× comm / 2.16× throughput",
  paper: {
    id: "zeropp-paper",
    title: "ZeRO++: Extremely Efficient Collective Communication for Giant Model Training",
    publisher: "DeepSpeed / Microsoft",
    url: "https://arxiv.org/abs/2306.10209",
  },
});

const mixZeroPlusPlus = deepSpeedEvent({
  id: "tech-deepspeed-mix-zero-plus-plus",
  date: "2023-08-31",
  title: "Mixed Precision ZeRO++ (MixZ++)",
  tutorialSlug: "mixed_precision_zeropp",
  tutorialFile: "mixed_precision_zeropp.md",
  category: "并行方案",
  family: "并行系统",
  summary: "在 ZeRO++ 上为低精度参数、梯度和高精度优化器状态安排不同的数据布局与更新路径。",
  situation: "低精度训练减少计算与存储，但高精度主状态、通信布局和参数更新仍可能形成峰值。",
  target: "同时降低大模型训练的显存、通信和更新开销。",
  action: "使用低精度参数副本参与前后向，把高精度更新路径与 ZeRO++ 通信优化组合。",
  result: "官方教程给出完整配置与适用边界；具体加速需在目标模型、精度和网络上复测。",
  mechanism: "mixed-precision parameter path + ZeRO++ communication path + high-precision optimizer ownership。",
  bestFor: "需要 ZeRO++ 且已采用 BF16/FP16 训练的大模型。",
  experiment: "以官方 MixZ++ 教程配置为依据，不把跨论文倍数拼接成统一收益。",
  computeMemory: "低精度副本降低常驻/通信体积，但高精度主状态与临时 buffer 仍形成模型状态下限。",
  parallelism: "ZeRO++ data parallel。",
  limitations: "精度、optimizer 兼容性和额外副本峰值需逐模型验证。",
  availability: "DeepSpeed Mixed Precision ZeRO++ 教程与配置公开。",
  tags: ["MixZ++", "Mixed Precision", "ZeRO++"],
});

const autoTp = deepSpeedEvent({
  id: "tech-deepspeed-autotp",
  date: "2023-02-21",
  title: "Automatic Tensor Parallelism (AutoTP)",
  tutorialSlug: "automatic-tensor-parallelism",
  tutorialFile: "automatic-tensor-parallelism.md",
  category: "并行方案",
  family: "并行系统",
  summary: "根据模型层结构、预设或 Hugging Face `tp_plan` 自动生成张量并行切分，减少逐模型手写 injection policy。",
  situation: "Tensor Parallel 通常要求按模型结构维护切分规则，模型版本变化会带来适配成本。",
  target: "自动识别可切分层并生成行/列并行规则，同时保留自定义覆盖能力。",
  action: "推理路径通过 AutoTP 注入替换层；训练路径可结合 DP、ZeRO 0/1/2、preset、正则规则与 Hugging Face `tp_plan`。",
  result: "官方实现支持多类 Hugging Face 模型；训练 AutoTP 目前明确不支持 ZeRO Stage 3。",
  mechanism: "模型解析 → layer policy/spec → 权重分片 → TP collective → 输出合并。",
  bestFor: "结构符合 Transformer 常见模式、希望降低 TP 接入成本的训练或推理。",
  experiment: "官方教程的支持模型与配置路径；新模型仍需检查融合层、GQA 和整除约束。",
  computeMemory: "参数和大矩阵按 TP 度分片；通信 buffer、复制层与 activation 不保证严格按 TP 度反比。",
  parallelism: "Tensor Parallel，可在训练中组合 DP 与 ZeRO 0/1/2。",
  limitations: "维度必须可整除；自定义/融合层可能需要 pattern 或 layer spec；训练不支持 ZeRO-3。",
  availability: "DeepSpeed inference AutoTP 与 training AutoTP 已有官方教程。",
  tags: ["AutoTP", "Tensor Parallel", "Hugging Face"],
});

const oneBitAdam = deepSpeedEvent({
  id: "tech-deepspeed-one-bit-adam",
  date: "2020-09-09",
  title: "1-bit Adam",
  tutorialSlug: "onebit-adam",
  tutorialFile: "onebit-adam.md",
  category: "算法流程",
  family: "优化器",
  summary: "在预热后对 Adam 的梯度通信做 1-bit 压缩，并用误差反馈补偿量化残差。",
  situation: "数据并行 Adam 在大规模和慢网络上被梯度 all-reduce 通信限制。",
  target: "保留 Adam 收敛行为的同时大幅减少通信量。",
  action: "先用普通 Adam 预热，再冻结方差项，量化通信梯度并累积 compression error。",
  result: "官方教程标题给出最高 5× 通信量下降和 3.4× 训练加速；只对论文实验配置成立。",
  mechanism: "warmup → variance freeze → 1-bit compressed all-reduce → error compensation。",
  bestFor: "通信瓶颈显著、可接受优化器阶段切换的数据并行训练。",
  experiment: "BERT/GPT 等论文任务与 Ethernet/InfiniBand 条件。",
  computeMemory: "增加误差反馈状态；降低网络传输而非模型状态本身。",
  parallelism: "Data Parallel optimizer communication。",
  limitations: "需要预热与方差冻结；不等价于任意 Adam 配置的无损替换。",
  availability: "DeepSpeed `OneBitAdam` 可用，官方更推荐评估后续 0/1 Adam。",
  tags: ["1-bit Adam", "Gradient Compression", "Error Feedback"],
  score: "up to 5× less communication / 3.4× faster",
  paper: {
    id: "one-bit-adam-paper",
    title: "1-bit Adam: Communication Efficient Large-Scale Training with Adam's Convergence Speed",
    publisher: "ICML",
    url: "https://arxiv.org/abs/2102.02888",
  },
});

const oneBitLamb = deepSpeedEvent({
  id: "tech-deepspeed-one-bit-lamb",
  date: "2021-04-20",
  title: "1-bit LAMB",
  tutorialSlug: "onebit-lamb",
  tutorialFile: "onebit-lamb.md",
  category: "算法流程",
  family: "优化器",
  summary: "把 1-bit 压缩扩展到适合超大 batch 的 LAMB，同时校正 layer-wise trust ratio。",
  situation: "LAMB 适合大 batch，但其梯度通信仍随 GPU 数增长。",
  target: "兼顾 LAMB 的大 batch 收敛与 1-bit 通信效率。",
  action: "预热后冻结部分统计量，对压缩梯度做误差反馈，并设计量化兼容的 trust-ratio 更新。",
  result: "论文证明可减少通信并保持目标任务收敛；收益仍受 batch、网络与预热阶段影响。",
  mechanism: "1-bit gradient compression + error feedback + LAMB layer-wise scaling。",
  bestFor: "BERT 类大 batch、通信受限的分布式训练。",
  experiment: "论文 BERT 预训练等任务；不能直接外推到所有 optimizer/model。",
  computeMemory: "增加 compression error 状态，降低梯度通信体积。",
  parallelism: "Data Parallel optimizer communication。",
  limitations: "实现与超参数更复杂，依赖 NCCL/MPI 兼容路径和预热切换。",
  availability: "DeepSpeed `OneBitLamb` 教程与实现公开。",
  tags: ["1-bit LAMB", "Large Batch", "Gradient Compression"],
  paper: {
    id: "one-bit-lamb-paper",
    title: "1-bit LAMB: Communication Efficient Large-Scale Large-Batch Training",
    publisher: "HiPC",
    url: "https://arxiv.org/abs/2104.06069",
  },
});

const zeroOneAdam = deepSpeedEvent({
  id: "tech-deepspeed-zero-one-adam",
  date: "2022-03-10",
  title: "0/1 Adam",
  tutorialSlug: "zero-one-adam",
  tutorialFile: "zero-one-adam.md",
  category: "算法流程",
  family: "优化器",
  summary: "在 1-bit Adam 基础上加入方差同步与局部更新两个阶段，减少对永久冻结方差的依赖。",
  situation: "1-bit Adam 的固定方差冻结限制了适用性，局部 optimizer step 仍可进一步减少通信。",
  target: "降低通信同时改善 Adam 状态更新的稳定性与通用性。",
  action: "在压缩同步阶段与本地更新阶段之间切换，周期性校准方差并保持误差反馈。",
  result: "论文和教程展示比 1-bit Adam 更灵活的通信/收敛折中；具体收益需按模型和同步周期复测。",
  mechanism: "compressed synchronization phase + local-step phase + variance state correction。",
  bestFor: "慢网络、长训练、需要比永久方差冻结更稳健的 Adam 训练。",
  experiment: "论文中的 GPT/BERT 类任务与不同网络；不把峰值加速视为通用常数。",
  computeMemory: "保留 optimizer/error 状态，主要优化通信频率与体积。",
  parallelism: "Data Parallel optimizer communication。",
  limitations: "同步周期和局部步数影响收敛；配置复杂度高于标准 Adam。",
  availability: "DeepSpeed `ZeroOneAdam` 教程和实现公开。",
  tags: ["0/1 Adam", "Local Step", "Compressed Optimizer"],
  paper: {
    id: "zero-one-adam-paper",
    title: "Maximizing Communication Efficiency for Large-scale Training via 0/1 Adam",
    publisher: "DeepSpeed / Microsoft",
    url: "https://arxiv.org/abs/2202.06009",
  },
});

const domino = deepSpeedEvent({
  id: "tech-deepspeed-domino",
  date: "2024-12-13",
  title: "Domino Communication Hiding",
  tutorialSlug: "domino",
  tutorialFile: "domino.md",
  category: "并行方案",
  family: "并行系统",
  summary: "把张量并行输入和权重切成可独立 tile，让一个 tile 的 collective 与另一个 tile 的 GEMM 重叠。",
  situation: "传统 TP 在 GEMM 后等待 AllReduce/ReduceScatter，通信暴露形成 GPU idle。",
  target: "通过通用 tensor slicing 和调度隐藏大部分 TP 通信。",
  action: "沿 batch/输出维切 tile，使用异步通信流和依赖事件交错 local compute 与 collective。",
  result: "论文在 DGX-H100 集群报告相对 Megatron-LM 最高约 1.3×；这不是任意拓扑的保证。",
  mechanism: "tile independence + async collective + compute/communication overlap scheduler。",
  bestFor: "TP collective 暴露明显且 GEMM 足以覆盖通信的训练。",
  experiment: "2/4 台 DGX-H100 的论文测试；需要重新测量目标 topology、microbatch 和 stream contention。",
  computeMemory: "增加多个 tile 的在途 activation/buffer，以换取通信隐藏。",
  parallelism: "Tensor Parallel，可与其他并行维度组合但会争用流和带宽。",
  limitations: "重叠不等于消除字节；小 GEMM、拥塞或依赖过紧时收益下降。",
  availability: "DeepSpeedExamples 提供 Domino 教程路径。",
  tags: ["Domino", "Communication Hiding", "Tensor Slicing"],
  score: "up to 1.3×",
  paper: {
    id: "domino-paper",
    title: "Domino: Eliminating Communication in LLM Training via Generic Tensor Slicing and Overlapping",
    publisher: "Microsoft Research",
    url: "https://arxiv.org/abs/2409.15241",
  },
});

const deepNvme = deepSpeedEvent({
  id: "tech-deepspeed-deepnvme",
  date: "2024-09-04",
  title: "DeepNVMe",
  tutorialSlug: "deepnvme",
  tutorialFile: "deepnvme.md",
  category: "高效算子",
  family: "高效算子",
  summary: "提供 tensor 与 NVMe 之间的异步 I/O、buffer 管理和并发调度，用持久存储扩展训练容量。",
  situation: "CPU 内存也不足时，直接文件 I/O 的同步、拷贝与小请求开销会拖慢 offload。",
  target: "让 NVMe 成为可流水的数据层，而不是训练主循环中的阻塞文件操作。",
  action: "使用 DeepNVMe async I/O handle、pinned buffer、并发队列与读写重叠搬运 tensor。",
  result: "官方教程给出 basic、pinned、GDS 与性能调优路径；吞吐必须在本机盘阵和 NUMA 上测量。",
  mechanism: "tensor buffer → async I/O queue → NVMe；prefetch/read 与 compute、writeback 重叠。",
  bestFor: "ZeRO-Infinity、超大 checkpoint 和超出 host RAM 的 tensor/offload 工作负载。",
  experiment: "官方 DeepNVMe 示例；无统一硬件倍数。",
  computeMemory: "用 NVMe 容量换更高延迟，额外需要 host/GPU staging buffer 和队列深度。",
  parallelism: "I/O 并发，可服务 ZeRO/Checkpoint 等并行训练路径。",
  limitations: "受 SSD、文件系统、PCIe、NUMA、queue depth 和 block size 约束。",
  availability: "DeepSpeed `deepspeed.ops.aio` / DeepNVMe 教程公开。",
  tags: ["DeepNVMe", "NVMe Offload", "Async I/O"],
});

const ulyssesOffload = deepSpeedEvent({
  id: "tech-deepspeed-ulysses-offload",
  date: "2024-12-05",
  title: "Ulysses-Offload / FPDT",
  tutorialSlug: "ulysses-offload",
  tutorialFile: "ulysses-offload.md",
  category: "并行方案",
  family: "并行系统",
  summary: "在 Ulysses sequence parallel 上按全局 chunk 计算 Attention，并把暂不用的 Q/K/V 与反向状态卸载到 pinned CPU。",
  situation: "Ulysses 已分摊序列，但单 rank 的 Attention 状态和非 Attention activation 仍限制百万 token。",
  target: "把长序列 GPU 峰值变成可流水的小工作集。",
  action: "按全局 chunk 切序列，A2A 重排 heads/sequence，使用双缓冲重叠 CPU offload/prefetch，并分块 FFN 与 loss。",
  result: "FPDT 论文报告同硬件最长序列最高 16×，8B 模型可在 4 GPU 训练 2M token、MFU 超过 55%；边界取决于论文硬件。",
  mechanism: "Ulysses A2A + global chunk + pinned-CPU state offload + double buffering。",
  bestFor: "Ulysses Attention state 已成为峰值、CPU RAM 充足且 PCIe 可被计算覆盖的百万 token 训练。",
  experiment: "FPDT 论文 A100 配置与 Megatron-DeepSpeed 教程实现。",
  computeMemory: "GPU 包含随 S/P 的基座和固定 chunk 工作区；CPU 另保存卸载状态，因此不严格随 P 反比。",
  parallelism: "Sequence Parallel / Ulysses，可再组合模型状态分片。",
  limitations: "S、SP 度和 chunk 需满足整除；依赖 FlashAttention、pinned memory、PCIe 与定制 autograd。",
  availability: "Megatron-DeepSpeed 的 Ulysses-Offload 教程路径公开。",
  tags: ["Ulysses-Offload", "FPDT", "Sequence Parallel"],
  score: "up to 16× sequence / 2M tokens",
  paper: {
    id: "fpdt-paper",
    title: "Fully Pipelined Distributed Transformer Training with In-Memory Tensor Offloading",
    publisher: "Microsoft / DeepSpeed",
    url: "https://arxiv.org/abs/2408.16978",
  },
});

const zenFlow = deepSpeedEvent({
  id: "tech-deepspeed-zenflow",
  date: "2025-08-15",
  title: "ZenFlow",
  tutorialSlug: "zenflow",
  tutorialFile: "zenflow.md",
  category: "算法流程",
  family: "优化器",
  summary: "扩展 ZeRO-Offload，选择重要梯度高频更新，并让其他梯度异步、低频更新，以减少 CPU optimizer stall。",
  situation: "CPU optimizer offload 会让 GPU 在 optimizer step 和梯度传输期间停顿。",
  target: "把 CPU 引发的 stall 从关键路径移开，同时保持可控的更新近似。",
  action: "按重要性选择 top-k 梯度，配置重选/更新间隔，并让通信和更新与后续训练重叠。",
  result: "官方教程提供 Stage 1/2 的配置和 GLUE fine-tuning 路径；实际收益需结合收敛和 stall profile 判断。",
  mechanism: "selective gradient update + asynchronous CPU optimizer + overlap。",
  bestFor: "ZeRO-Offload 已受 CPU optimizer stall 限制的训练。",
  experiment: "DeepSpeed ZenFlow GLUE 示例；不把示例可运行等同为所有模型精度证明。",
  computeMemory: "保留选择元数据和异步在途状态；主要降低关键路径等待。",
  parallelism: "ZeRO Stage 1/2 optimizer offload。",
  limitations: "更新间隔和 top-k 是近似，会影响收敛；依赖可隐藏的 CPU/GPU overlap。",
  availability: "DeepSpeed `zero_optimization.zenflow` 配置公开。",
  tags: ["ZenFlow", "Selective Update", "CPU Offload"],
});

const dataStates = deepSpeedEvent({
  id: "tech-deepspeed-datastates",
  date: "2025-10-23",
  title: "DataStates-LLM Async Checkpoint",
  tutorialSlug: "datastates-async-checkpointing",
  tutorialFile: "datastates-async-checkpointing.md",
  category: "并行方案",
  family: "并行系统",
  summary: "利用前后向期间模型与优化器状态不可变的窗口，把 checkpoint 捕获、host cache 和持久化写入解耦。",
  situation: "同步 checkpoint 会停止训练并等待 GPU→CPU→存储完整落盘。",
  target: "缩短 checkpoint 暴露时间，并让持久化 I/O 在后台完成。",
  action: "用 pinned host cache 捕获状态，采用 lazy asynchronous multi-level flush，再按 save interval 触发。",
  result: "论文与官方教程报告最高 48× checkpoint 加速和 2.2× 端到端训练加速；当前适用范围较窄。",
  mechanism: "immutable-state window → non-blocking transfer → host cache → asynchronous storage flush。",
  bestFor: "checkpoint 频繁且 I/O 已成为训练停顿的大模型任务。",
  experiment: "DataStates-LLM 论文与 DeepSpeed 集成；教程明确列出 CUDA/ZeRO-1 等限制。",
  computeMemory: "用 pinned host cache 容量换训练侧低停顿；持久化带宽仍决定后台积压。",
  parallelism: "当前 DeepSpeed 集成主要验证 ZeRO Stage 1。",
  limitations: "仅 NVIDIA CUDA；已测 ZeRO-1 且无 offload；尚不支持 universal/elastic checkpoint。",
  availability: "DataStates-LLM 与 DeepSpeed 教程公开，但仍属受限集成。",
  tags: ["DataStates", "Async Checkpoint", "Pinned Memory"],
  score: "up to 48× checkpoint / 2.2× end-to-end",
  paper: {
    id: "datastates-paper",
    title: "DataStates-LLM: Lazy Asynchronous Checkpointing for Large Language Models",
    publisher: "DataStates",
    url: "https://arxiv.org/abs/2406.10707",
  },
});

const deepSpeedMoe = deepSpeedEvent({
  id: "tech-deepspeed-moe",
  date: "2021-08-17",
  title: "DeepSpeed-MoE",
  tutorialSlug: "mixture-of-experts",
  tutorialFile: "mixture-of-experts.md",
  category: "模型结构",
  family: "MoE",
  summary: "把稀疏专家层、router、expert parallel group 和 capacity/drop 策略接入 DeepSpeed 训练。",
  situation: "稠密模型增加参数会同步增加每 token 计算，难以继续扩展模型容量。",
  target: "让每个 token 只激活少数专家，以较低计算获得更大参数容量。",
  action: "将 Transformer FFN 替换为 MoE layer，配置 num_experts、ep_size、top-k、capacity 与 auxiliary loss。",
  result: "官方教程提供训练与并行配置；质量和成本收益必须在相同 token、模型与硬件口径比较。",
  mechanism: "router top-k → token dispatch → local expert FFN → token combine。",
  bestFor: "需要扩展参数容量且集群具备高效 all-to-all 的训练。",
  experiment: "DeepSpeed MoE 教程与论文模型；不把理论稀疏 FLOPs 等同端到端速度。",
  computeMemory: "专家参数按 EP 分布；router、dispatch buffer 和负载不均引入额外峰值。",
  parallelism: "Expert Parallel，可组合 DP/TP/PP。",
  limitations: "负载均衡、capacity overflow、all-to-all 和 checkpoint 布局复杂。",
  availability: "DeepSpeed `deepspeed.moe.layer.MoE` 可用。",
  tags: ["DeepSpeed-MoE", "Expert Parallel", "Sparse Model"],
  paper: {
    id: "deepspeed-moe-paper",
    title: "DeepSpeed-MoE: Advancing Mixture-of-Experts Inference and Training",
    publisher: "ICML",
    url: "https://arxiv.org/abs/2201.05596",
  },
});

const moeInference = deepSpeedEvent({
  id: "tech-deepspeed-moe-inference",
  date: "2022-01-18",
  title: "DeepSpeed-MoE Inference",
  tutorialSlug: "mixture-of-experts-inference",
  tutorialFile: "mixture-of-experts-inference.md",
  category: "并行方案",
  family: "MoE",
  summary: "为大规模 MoE 推理联合 expert parallel、tensor parallel、kernel injection 和 checkpoint 重排。",
  situation: "MoE 推理的专家参数、token dispatch 和小 batch GEMM 让训练布局不能直接高效复用。",
  target: "在多 GPU/多节点上降低 MoE 推理延迟与成本。",
  action: "按 ep_size/mp_size 映射 checkpoint，使用 inference engine、专家分布与融合 kernel 执行 token 路由。",
  result: "官方教程展示大规模 MoE 模型推理接入；性能依模型、batch、拓扑和 checkpoint 布局。",
  mechanism: "router dispatch + expert/tensor parallel + inference kernel injection + output combine。",
  bestFor: "参数量巨大、专家分布跨 GPU 的 MoE serving。",
  experiment: "DeepSpeed-MoE 论文和官方 inference tutorial。",
  computeMemory: "专家权重按 EP 分摊，但 token buffer、复制层和通信 workspace 形成峰值。",
  parallelism: "Expert Parallel + Tensor Parallel。",
  limitations: "小 batch、跨节点 all-to-all、专家负载和 checkpoint 转换可能主导延迟。",
  availability: "DeepSpeed inference engine 的 MoE 路径公开；支持模型需逐版本核验。",
  tags: ["MoE Inference", "Expert Parallel", "Kernel Injection"],
  paper: {
    id: "moe-inference-paper",
    title: "DeepSpeed-MoE: Advancing Mixture-of-Experts Inference and Training",
    publisher: "ICML",
    url: "https://arxiv.org/abs/2201.05596",
  },
});

const modelCompression = deepSpeedEvent({
  id: "tech-deepspeed-model-compression",
  date: "2022-07-19",
  title: "DeepSpeed Model Compression",
  tutorialSlug: "model-compression",
  tutorialFile: "model-compression.md",
  category: "算法流程",
  family: "量化训练",
  summary: "把量化、稀疏、head/layer reduction 和知识蒸馏组织为可组合压缩流水。",
  situation: "单一压缩技术常把训练脚本、模型结构和部署路径耦合，难以组合与复现。",
  target: "用统一配置表达多个压缩方法，并兼顾训练与部署。",
  action: "在 compression config 中声明 weight/activation quantization、sparse pruning、row/head/channel pruning 与 distillation。",
  result: "官方教程展示 Hugging Face 等模型的组合压缩路径；效果受目标模型、任务和校准数据限制。",
  mechanism: "compression schedule + model module replacement/masking + distillation objective。",
  bestFor: "需要在大小、吞吐和质量之间联合调优的模型压缩。",
  experiment: "DeepSpeed Compression 教程及 Extreme Compression 论文；跨任务数字不可直接比较。",
  computeMemory: "降低最终权重/计算，但训练期 mask、teacher、fake-quant 与稀疏元数据可能增加峰值。",
  parallelism: "可与 DeepSpeed 训练并行组合，部署后取决于 kernel 对压缩格式的支持。",
  limitations: "组合空间大；压缩率不自动转化为硬件速度，质量需任务级复测。",
  availability: "DeepSpeed Compression Library 教程与配置公开。",
  tags: ["Model Compression", "Quantization", "Pruning", "Distillation"],
  paper: {
    id: "extreme-compression-paper",
    title: "Extreme Compression for Pre-trained Transformers Made Simple and Efficient",
    publisher: "NeurIPS",
    url: "https://arxiv.org/abs/2206.01859",
  },
});

const moq = deepSpeedEvent({
  id: "tech-deepspeed-moq",
  date: "2021-05-24",
  title: "Mixture-of-Quantization (MoQ)",
  tutorialSlug: "MoQ-tutorial",
  tutorialFile: "MoQ-tutorial.md",
  category: "算法流程",
  family: "量化训练",
  summary: "从高 bit 逐步降到目标 bit，并可用层级二阶敏感度动态放慢易受损层的量化日程。",
  situation: "直接从 FP16/FP32 切到低 bit QAT 会产生较大的训练扰动和层间敏感度差异。",
  target: "让模型逐级适应更低精度，尽量保持下游任务质量。",
  action: "配置 start_bits、target_bits、period、offset、groups 和可选 eigenvalue schedule，在 GLUE fine-tuning 中逐级降 bit。",
  result: "官方教程的 GLUE 表显示 MoQ 在其设置中保持或改善平均准确率；不是对所有模型的保证。",
  mechanism: "progressive bit schedule + grouped QAT + optional layer-wise second-order sensitivity。",
  bestFor: "可接受 QAT 成本、目标是 8-bit 等低精度的 Transformer fine-tuning。",
  experiment: "BERT/GLUE 教程结果；eigenvalue 计算会显著增加训练时间。",
  computeMemory: "低 bit 目标降低部署权重/计算；训练期 fake-quant 与二阶估计增加开销。",
  parallelism: "训练并行保持不变，量化 schedule 在各层执行。",
  limitations: "eigenvalue 可能 NaN/Inf、调参复杂且不保证精度提升。",
  availability: "DeepSpeed MoQ 教程与配置公开。",
  tags: ["MoQ", "QAT", "Progressive Quantization"],
});

const flopsProfiler = deepSpeedEvent({
  id: "tech-deepspeed-flops-profiler",
  date: "2021-02-10",
  title: "DeepSpeed FLOPs Profiler",
  tutorialSlug: "flops-profiler",
  tutorialFile: "flops-profiler.md",
  category: "高效算子",
  family: "高效算子",
  summary: "按 module 汇总参数量、MACs/FLOPs、时延和吞吐，把模型理论计算与运行热点对齐。",
  situation: "只看总 step time 无法判断瓶颈来自模型结构、某层计算还是框架开销。",
  target: "用模块级统计定位最昂贵的算子和层。",
  action: "在指定 profile step 注册 hooks，聚合 module 参数、MACs、FLOPs 与 duration，并输出层级报告。",
  result: "提供结构化 profiler 报告；FLOPs 是估算，不等于硬件实际利用率。",
  mechanism: "module hooks + operator FLOPs formulas + hierarchical aggregation。",
  bestFor: "模型级 compute hotspot、FLOPs budget 与结构对比。",
  experiment: "官方模型示例；不把估算 FLOPs 当 wall-clock benchmark。",
  computeMemory: "分析开销主要来自 hooks 与统计；不直接降低显存。",
  parallelism: "可在 DeepSpeed engine 中运行，分布式结果需理解 rank 局部与全局口径。",
  limitations: "自定义/融合算子可能缺失公式；动态控制流和通信不由 FLOPs 完整描述。",
  availability: "DeepSpeed Flops Profiler API 与教程公开。",
  tags: ["FLOPs Profiler", "MACs", "Latency"],
});

const pytorchProfiler = deepSpeedEvent({
  id: "tech-deepspeed-pytorch-profiler",
  date: "2021-09-21",
  title: "PyTorch Profiler with DeepSpeed",
  tutorialSlug: "pytorch-profiler",
  tutorialFile: "pytorch-profiler.md",
  category: "高效算子",
  family: "高效算子",
  summary: "在 DeepSpeed 训练中捕获 CPU/CUDA operator、shape、stack 与 trace，定位真实执行时延。",
  situation: "FLOPs 不能揭示 kernel launch、同步、CPU stall 和通信等待。",
  target: "从真实运行 trace 找到 step 内关键路径。",
  action: "配置 profiler schedule、activities、tensorboard trace handler 与 DeepSpeed 训练 step。",
  result: "可在 TensorBoard/trace 中检查 CPU/CUDA 热点；采样窗口本身会增加开销。",
  mechanism: "runtime event tracing + scheduled capture + trace export。",
  bestFor: "kernel、CPU、同步和通信时序的性能调试。",
  experiment: "官方 DeepSpeed + PyTorch Profiler 示例。",
  computeMemory: "记录 stack/shape/memory 会增加 host 内存、trace 和运行开销。",
  parallelism: "每 rank profiler；多 rank 需要时间对齐和 trace 汇总。",
  limitations: "长时间全量采集代价高；trace 解释需区分异步提交与 GPU 执行。",
  availability: "PyTorch Profiler 与 DeepSpeed 教程公开。",
  tags: ["PyTorch Profiler", "Trace", "Performance Debugging"],
});

const communicationLogging = deepSpeedEvent({
  id: "tech-deepspeed-communication-logging",
  date: "2022-07-25",
  title: "Communication Logging",
  tutorialSlug: "comms-logging",
  tutorialFile: "comms-logging.md",
  category: "高效算子",
  family: "高效算子",
  summary: "包装 DeepSpeed collective，按操作、消息大小和调用位置记录通信时延与带宽。",
  situation: "分布式训练慢时，仅看 NCCL 总时间难以定位是哪类 collective、哪个尺寸或哪个调用点。",
  target: "把通信热点映射回模型和并行执行路径。",
  action: "启用 communication logger，对 all-reduce、all-gather、reduce-scatter 等调用计时并汇总。",
  result: "可输出各类 collective 的次数、时延和消息规模；logger 本身不是通信优化。",
  mechanism: "collective wrapper → timing/synchronization → aggregation/report。",
  bestFor: "诊断 DP/TP/PP/EP 中的通信暴露与消息粒度。",
  experiment: "官方 comm logging 教程；测量开销需通过关闭 logger 的对照验证。",
  computeMemory: "少量统计状态；同步式计时可能改变原始 overlap。",
  parallelism: "覆盖 DeepSpeed communication backend 的 collective。",
  limitations: "计时会扰动异步执行；不能单独解释网络拥塞根因。",
  availability: "DeepSpeed communication logging API 公开。",
  tags: ["Communication Logging", "Collective", "Bandwidth"],
});

const autotuning = deepSpeedEvent({
  id: "tech-deepspeed-autotuning",
  date: "2021-11-13",
  title: "DeepSpeed Autotuning",
  tutorialSlug: "autotuning",
  tutorialFile: "autotuning.md",
  category: "算法流程",
  family: "训练算法",
  summary: "围绕 micro-batch、ZeRO stage 和相关配置运行受控试验，以吞吐等目标选择 DeepSpeed 配置。",
  situation: "DeepSpeed 配置空间大，手工调整 batch、ZeRO 与 offload 很难找到目标硬件的最优点。",
  target: "自动搜索可运行且性能较好的配置。",
  action: "定义 tuning space、metric、资源与 early stopping，运行多个 experiment 并选择 best config。",
  result: "能减少人工试错，但结果只对指定模型、硬件、数据和目标函数有效。",
  mechanism: "configuration search → trial launch → metric collection → pruning/ranking。",
  bestFor: "已有稳定训练脚本，希望优化吞吐或资源配置。",
  experiment: "官方 Autotuning 教程；搜索成本和重现性需纳入预算。",
  computeMemory: "不直接改变内存；通过搜索选择 batch/stage/offload 组合。",
  parallelism: "搜索 DeepSpeed data/model parallel 相关配置。",
  limitations: "试验成本高，错误 trial、噪声和动态环境会影响排名。",
  availability: "DeepSpeed Autotuning 配置与命令公开。",
  tags: ["Autotuning", "Configuration Search", "Throughput"],
});

const monitor = deepSpeedEvent({
  id: "tech-deepspeed-monitor",
  date: "2022-06-16",
  title: "DeepSpeed Monitor",
  tutorialSlug: "monitor",
  tutorialFile: "monitor.md",
  category: "高效算子",
  family: "高效算子",
  summary: "把训练 metric 统一写入 TensorBoard、WandB、CSV 等后端，形成长期可比较的实验记录。",
  situation: "多 rank 训练的 loss、lr、samples/s 和自定义指标容易散落，难以统一追踪。",
  target: "用同一 DeepSpeed config 控制多个监控后端。",
  action: "配置 tensorboard、wandb、csv_monitor 等 backend，由 engine 在约定 step 写 metric。",
  result: "统一实验日志入口；它提供可观测性，不替代 profiler 或异常诊断。",
  mechanism: "engine events → rank-aware metric emission → backend writer。",
  bestFor: "长期训练曲线、实验对比和外部 dashboard。",
  experiment: "官方 Monitor 教程；吞吐影响应在实际日志频率下测量。",
  computeMemory: "主要是 host 日志与 I/O 开销；高频写入可能影响训练。",
  parallelism: "分布式 rank-aware logging，通常控制主 rank 写出。",
  limitations: "后端可用性、网络和日志频率影响稳定性；指标定义仍由训练代码负责。",
  availability: "DeepSpeed TensorBoard/WandB/CSV monitor 配置公开。",
  tags: ["Monitor", "TensorBoard", "WandB", "CSV"],
});

export const deepSpeedTechnologyLanes: TimelineLane[] = [
  {
    id: "training-tech-deepspeed-memory",
    group: "DeepSpeed 专栏 / 01",
    title: "内存与并行编排",
    description: "ZeRO-Offload、ZeRO++、MixZ++ 与 AutoTP",
    color: "amber",
    events: [zeroOffload, zeroPlusPlus, mixZeroPlusPlus, autoTp],
  },
  {
    id: "training-tech-deepspeed-communication",
    group: "DeepSpeed 专栏 / 02",
    title: "通信压缩与隐藏",
    description: "1-bit Adam、1-bit LAMB、0/1 Adam 与 Domino",
    color: "violet",
    events: [oneBitAdam, oneBitLamb, zeroOneAdam, domino],
  },
  {
    id: "training-tech-deepspeed-io",
    group: "DeepSpeed 专栏 / 03",
    title: "存储卸载与异步流水",
    description: "DeepNVMe、Ulysses-Offload、ZenFlow 与 DataStates",
    color: "green",
    events: [deepNvme, ulyssesOffload, zenFlow, dataStates],
  },
  {
    id: "training-tech-deepspeed-moe",
    group: "DeepSpeed 专栏 / 04",
    title: "MoE 与模型压缩",
    description: "DeepSpeed-MoE、MoE Inference、Model Compression 与 MoQ",
    color: "cyan",
    events: [deepSpeedMoe, moeInference, modelCompression, moq],
  },
  {
    id: "training-tech-deepspeed-observability",
    group: "DeepSpeed 专栏 / 05",
    title: "性能观测与自动调优",
    description: "FLOPs/PyTorch Profiler、通信日志、Autotuning 与 Monitor",
    color: "amber",
    events: [flopsProfiler, pytorchProfiler, communicationLogging, autotuning, monitor],
  },
];

export const deepSpeedTechnologies = deepSpeedTechnologyLanes.flatMap((lane) => lane.events);
