export interface RawModelCatalogEntry {
  id: string;
  name: string;
  org: string;
  releaseDate: string;
  access: "open" | "api" | "pending";
  license: string | null;
  modality: string;
  totalParamsB: number | null;
  activeParamsB: number | null;
  contextK: number | null;
  weightSizeGB: number | null;
  trainingTokensT: number | null;
  aaIntelligence: number | null;
  aaAgentic: number | null;
  outputTokensPerSecond: number | null;
  blendedPricePerMTok: number | null;
  primarySourceUrl: string;
  aaUrl: string | null;
}

export const representativeModelCatalog: RawModelCatalogEntry[] = [
  { id: "chatgpt-gpt35", name: "ChatGPT / GPT-3.5 Turbo", org: "OpenAI", releaseDate: "2022-11-30", access: "api", license: "Proprietary", modality: "text→text", totalParamsB: null, activeParamsB: null, contextK: 4.096, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 3.6, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 0.60, primarySourceUrl: "https://openai.com/index/chatgpt/", aaUrl: "https://artificialanalysis.ai/models/gpt-35-turbo" },
  { id: "gpt-4", name: "GPT-4", org: "OpenAI", releaseDate: "2023-03-14", access: "api", license: "Proprietary", modality: "text→text", totalParamsB: null, activeParamsB: null, contextK: 8.192, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 7.0, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 33.00, primarySourceUrl: "https://openai.com/index/gpt-4-research/", aaUrl: "https://artificialanalysis.ai/models/gpt-4" },
  { id: "gpt-4o-2024-11", name: "GPT-4o (Nov ’24)", org: "OpenAI", releaseDate: "2024-11-20", access: "api", license: "Proprietary", modality: "text+image+audio→text+audio", totalParamsB: null, activeParamsB: null, contextK: 128, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 11.2, aaAgentic: null, outputTokensPerSecond: 184.9, blendedPricePerMTok: 2.55, primarySourceUrl: "https://platform.openai.com/docs/models/gpt-4o", aaUrl: "https://artificialanalysis.ai/models/gpt-4o" },
  { id: "openai-o1", name: "o1", org: "OpenAI", releaseDate: "2024-12-05", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 200, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 23.4, aaAgentic: null, outputTokensPerSecond: 118.0, blendedPricePerMTok: 14.25, primarySourceUrl: "https://openai.com/o1/", aaUrl: "https://artificialanalysis.ai/models/o1" },
  { id: "gpt-5-high", name: "GPT-5 (high)", org: "OpenAI", releaseDate: "2025-08-07", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 400, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 34.7, aaAgentic: 25.7, outputTokensPerSecond: 99.2, blendedPricePerMTok: 1.338, primarySourceUrl: "https://openai.com/index/introducing-gpt-5/", aaUrl: "https://artificialanalysis.ai/models/gpt-5" },
  { id: "gpt-5-6-sol-max", name: "GPT-5.6 Sol (max)", org: "OpenAI", releaseDate: "2026-07-09", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 58.9, aaAgentic: 54.0, outputTokensPerSecond: 55.0, blendedPricePerMTok: 4.35, primarySourceUrl: "https://openai.com/index/gpt-5-6/", aaUrl: "https://artificialanalysis.ai/models/gpt-5-6-sol" },

  { id: "claude-1", name: "Claude 1", org: "Anthropic", releaseDate: "2023-03-14", access: "api", license: "Proprietary", modality: "text→text", totalParamsB: null, activeParamsB: null, contextK: 9, weightSizeGB: null, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://www.anthropic.com/news/introducing-claude", aaUrl: null },
  { id: "claude-3-opus", name: "Claude 3 Opus", org: "Anthropic", releaseDate: "2024-03-04", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 200, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 11.8, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 11.55, primarySourceUrl: "https://www.anthropic.com/news/claude-3-family", aaUrl: "https://artificialanalysis.ai/models/claude-3-opus" },
  { id: "claude-35-sonnet-june", name: "Claude 3.5 Sonnet (June ’24)", org: "Anthropic", releaseDate: "2024-06-20", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 200, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 8.3, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 2.31, primarySourceUrl: "https://www.anthropic.com/news/claude-3-5-sonnet", aaUrl: "https://artificialanalysis.ai/models/claude-35-sonnet-june-24" },
  { id: "claude-4-opus-thinking", name: "Claude 4 Opus (Reasoning)", org: "Anthropic", releaseDate: "2025-05-22", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 200, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 31.0, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 11.55, primarySourceUrl: "https://www.anthropic.com/news/claude-4", aaUrl: "https://artificialanalysis.ai/models/claude-4-opus-thinking" },
  { id: "claude-fable-5", name: "Claude Fable 5 (Adaptive/Max)", org: "Anthropic", releaseDate: "2026-06-09", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 59.9, aaAgentic: 52.8, outputTokensPerSecond: 64.5, blendedPricePerMTok: 7.70, primarySourceUrl: "https://www.anthropic.com/claude/fable", aaUrl: "https://artificialanalysis.ai/models/claude-fable-5" },

  { id: "gemini-1-ultra", name: "Gemini 1.0 Ultra", org: "Google", releaseDate: "2023-12-06", access: "api", license: "Proprietary", modality: "text+image+audio+video→text", totalParamsB: null, activeParamsB: null, contextK: 32.768, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 4.6, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://blog.google/technology/ai/google-gemini-ai/", aaUrl: "https://artificialanalysis.ai/models/gemini-1-0-ultra" },
  { id: "gemini-15-pro-sep", name: "Gemini 1.5 Pro (Sep ’24)", org: "Google", releaseDate: "2024-09-24", access: "api", license: "Proprietary", modality: "text+image+audio+video→text", totalParamsB: null, activeParamsB: null, contextK: 2000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 10.0, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://deepmind.google/technologies/gemini/pro/", aaUrl: "https://artificialanalysis.ai/models/gemini-1-5-pro" },
  { id: "gemini-25-pro", name: "Gemini 2.5 Pro", org: "Google", releaseDate: "2025-06-05", access: "api", license: "Proprietary", modality: "text+image+audio+video→text", totalParamsB: null, activeParamsB: null, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 25.8, aaAgentic: 7.1, outputTokensPerSecond: 137.9, blendedPricePerMTok: 1.338, primarySourceUrl: "https://blog.google/technology/google-deepmind/gemini-2-5-thinking-model-updates/", aaUrl: "https://artificialanalysis.ai/models/gemini-2-5-pro" },
  { id: "gemini-31-pro-preview", name: "Gemini 3.1 Pro Preview", org: "Google", releaseDate: "2026-02-19", access: "api", license: "Proprietary", modality: "text+image+audio+video→text", totalParamsB: null, activeParamsB: null, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 46.5, aaAgentic: 21.4, outputTokensPerSecond: 115.7, blendedPricePerMTok: 1.74, primarySourceUrl: "https://blog.google/technology/google-deepmind/gemini-3-1-pro/", aaUrl: "https://artificialanalysis.ai/models/gemini-3-1-pro-preview" },
  { id: "gemini-35-flash", name: "Gemini 3.5 Flash (high)", org: "Google", releaseDate: "2026-05-19", access: "api", license: "Proprietary", modality: "text+image+audio+video→text", totalParamsB: null, activeParamsB: null, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 50.2, aaAgentic: 37.4, outputTokensPerSecond: 156.8, blendedPricePerMTok: 1.305, primarySourceUrl: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-5/", aaUrl: "https://artificialanalysis.ai/models/gemini-3-5-flash" },

  { id: "llama-2-70b-chat", name: "Llama 2 Chat 70B", org: "Meta", releaseDate: "2023-07-18", access: "open", license: "Llama 2 Community License", modality: "text→text", totalParamsB: 70, activeParamsB: 70, contextK: 4.096, weightSizeGB: null, trainingTokensT: 2.0, aaIntelligence: 3.0, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://ai.meta.com/blog/llama-2/", aaUrl: "https://artificialanalysis.ai/models/llama-2-chat-70b" },
  { id: "llama-3-70b-instruct", name: "Llama 3 Instruct 70B", org: "Meta", releaseDate: "2024-04-18", access: "open", license: "Meta Llama 3 Community License", modality: "text→text", totalParamsB: 70, activeParamsB: 70, contextK: 8.192, weightSizeGB: null, trainingTokensT: 15.0, aaIntelligence: 3.5, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 0.86, primarySourceUrl: "https://ai.meta.com/blog/meta-llama-3/", aaUrl: "https://artificialanalysis.ai/models/llama-3-instruct-70b" },
  { id: "llama-31-405b-instruct", name: "Llama 3.1 Instruct 405B", org: "Meta", releaseDate: "2024-07-23", access: "open", license: "Llama 3.1 Community License", modality: "text→text", totalParamsB: 405, activeParamsB: 405, contextK: 128, weightSizeGB: null, trainingTokensT: 15.6, aaIntelligence: 8.5, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 4.824, primarySourceUrl: "https://ai.meta.com/blog/meta-llama-3-1/", aaUrl: "https://artificialanalysis.ai/models/llama-3-1-instruct-405b" },
  { id: "llama-4-maverick", name: "Llama 4 Maverick", org: "Meta", releaseDate: "2025-04-05", access: "open", license: "Llama 4 Community License", modality: "text+image→text", totalParamsB: 400, activeParamsB: 17, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 14.3, aaAgentic: 1.3, outputTokensPerSecond: 109.4, blendedPricePerMTok: 0.344, primarySourceUrl: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/", aaUrl: "https://artificialanalysis.ai/models/llama-4-maverick" },

  { id: "mistral-7b-instruct", name: "Mistral 7B Instruct", org: "Mistral AI", releaseDate: "2023-09-27", access: "open", license: "Apache-2.0", modality: "text→text", totalParamsB: 7, activeParamsB: 7, contextK: 8.192, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 2.1, aaAgentic: null, outputTokensPerSecond: 102.2, blendedPricePerMTok: 0.25, primarySourceUrl: "https://mistral.ai/news/announcing-mistral-7b", aaUrl: "https://artificialanalysis.ai/models/mistral-7b-instruct" },
  { id: "mixtral-8x7b-instruct", name: "Mixtral 8x7B Instruct", org: "Mistral AI", releaseDate: "2023-12-11", access: "open", license: "Apache-2.0", modality: "text→text", totalParamsB: 46.7, activeParamsB: 12.9, contextK: 32.768, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 2.4, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 0.475, primarySourceUrl: "https://mistral.ai/news/mixtral-of-experts", aaUrl: "https://artificialanalysis.ai/models/mixtral-8x7b-instruct" },
  { id: "mistral-large-1", name: "Mistral Large (Feb ’24)", org: "Mistral AI", releaseDate: "2024-02-26", access: "api", license: "Proprietary", modality: "text→text", totalParamsB: null, activeParamsB: null, contextK: 32.768, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 4.4, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 4.80, primarySourceUrl: "https://mistral.ai/news/mistral-large", aaUrl: "https://artificialanalysis.ai/models/mistral-large" },
  { id: "mistral-large-2-nov", name: "Mistral Large 2 (Nov ’24)", org: "Mistral AI", releaseDate: "2024-11-18", access: "open", license: "Mistral Research License", modality: "text→text", totalParamsB: 123, activeParamsB: 123, contextK: 128, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 9.1, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://mistral.ai/news/mistral-large-2407", aaUrl: "https://artificialanalysis.ai/models/mistral-large-2" },

  { id: "deepseek-v2-chat", name: "DeepSeek‑V2‑Chat", org: "DeepSeek", releaseDate: "2024-05-06", access: "open", license: "DeepSeek License Agreement", modality: "text→text", totalParamsB: 236, activeParamsB: 21, contextK: 128, weightSizeGB: null, trainingTokensT: 8.1, aaIntelligence: 3.6, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/deepseek-ai/DeepSeek-V2", aaUrl: "https://artificialanalysis.ai/models/deepseek-v2" },
  { id: "deepseek-v3-1226", name: "DeepSeek V3 (Dec ’24)", org: "DeepSeek", releaseDate: "2024-12-26", access: "open", license: "DeepSeek License Agreement", modality: "text→text", totalParamsB: 671, activeParamsB: 37, contextK: 128, weightSizeGB: 689, trainingTokensT: 14.8, aaIntelligence: 14.2, aaAgentic: 1.6, outputTokensPerSecond: null, blendedPricePerMTok: 0.413, primarySourceUrl: "https://github.com/deepseek-ai/DeepSeek-V3", aaUrl: "https://artificialanalysis.ai/models/deepseek-v3" },
  { id: "deepseek-r1-0528", name: "DeepSeek R1 0528", org: "DeepSeek", releaseDate: "2025-05-28", access: "open", license: "MIT", modality: "text→text", totalParamsB: 671, activeParamsB: 37, contextK: 128, weightSizeGB: 685, trainingTokensT: 14.8, aaIntelligence: 20.1, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 1.635, primarySourceUrl: "https://github.com/deepseek-ai/DeepSeek-R1", aaUrl: "https://artificialanalysis.ai/models/deepseek-r1" },
  { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro (max)", org: "DeepSeek", releaseDate: "2026-04-24", access: "open", license: "MIT", modality: "text→text", totalParamsB: 1600, activeParamsB: 49, contextK: 1048.576, weightSizeGB: 864.72, trainingTokensT: 33, aaIntelligence: 44.3, aaAgentic: 36.4, outputTokensPerSecond: 61.8, blendedPricePerMTok: 0.177, primarySourceUrl: "https://api-docs.deepseek.com/news/news260424/", aaUrl: "https://artificialanalysis.ai/models/deepseek-v4-pro" },

  { id: "kimi-k15", name: "Kimi k1.5", org: "Moonshot AI", releaseDate: "2025-01-20", access: "open", license: "Modified MIT", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 128, weightSizeGB: null, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://arxiv.org/abs/2501.12599", aaUrl: null },
  { id: "kimi-k2", name: "Kimi K2", org: "Moonshot AI", releaseDate: "2025-07-11", access: "open", license: "Modified MIT", modality: "text→text", totalParamsB: 1040, activeParamsB: 32.6, contextK: 128, weightSizeGB: 1029.19, trainingTokensT: 15.5, aaIntelligence: 19.4, aaAgentic: null, outputTokensPerSecond: 36.0, blendedPricePerMTok: 0.743, primarySourceUrl: "https://moonshotai.github.io/Kimi-K2/", aaUrl: "https://artificialanalysis.ai/models/kimi-k2" },
  { id: "kimi-k25", name: "Kimi K2.5", org: "Moonshot AI", releaseDate: "2026-01-27", access: "open", license: "Modified MIT", modality: "text+image+video→text", totalParamsB: 1040, activeParamsB: 32, contextK: 262.144, weightSizeGB: 595, trainingTokensT: 15, aaIntelligence: 35, aaAgentic: null, outputTokensPerSecond: 48.0, blendedPricePerMTok: 0.49, primarySourceUrl: "https://www.kimi.com/blog/kimi-k2-5", aaUrl: "https://artificialanalysis.ai/models/kimi-k2-5" },
  { id: "kimi-k26", name: "Kimi K2.6", org: "Moonshot AI", releaseDate: "2026-04-20", access: "open", license: "Modified MIT", modality: "text+image+video→text", totalParamsB: 1000, activeParamsB: 32, contextK: 256, weightSizeGB: 595.18, trainingTokensT: null, aaIntelligence: 44.2, aaAgentic: 30.3, outputTokensPerSecond: 45.1, blendedPricePerMTok: 0.702, primarySourceUrl: "https://www.kimi.com/blog/kimi-k2-6", aaUrl: "https://artificialanalysis.ai/models/kimi-k2-6" },
  { id: "kimi-k3", name: "Kimi K3", org: "Moonshot AI", releaseDate: "2026-07-16", access: "pending", license: null, modality: "text+image→text", totalParamsB: 2800, activeParamsB: null, contextK: 1048.576, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 57.1, aaAgentic: 50.1, outputTokensPerSecond: 62.0, blendedPricePerMTok: 2.31, primarySourceUrl: "https://www.kimi.com/blog/kimi-k3", aaUrl: "https://artificialanalysis.ai/models/kimi-k3" },

  { id: "glm-4", name: "GLM‑4", org: "Z.ai / Zhipu AI", releaseDate: "2024-01-16", access: "api", license: "Proprietary", modality: "text→text", totalParamsB: null, activeParamsB: null, contextK: 128, weightSizeGB: null, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/THUDM/GLM-4", aaUrl: null },
  { id: "glm-45", name: "GLM‑4.5 (Reasoning)", org: "Z.ai", releaseDate: "2025-07-28", access: "open", license: "MIT", modality: "text→text", totalParamsB: 355, activeParamsB: 32, contextK: 128, weightSizeGB: null, trainingTokensT: 23, aaIntelligence: 19.5, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://z.ai/blog/glm-4.5", aaUrl: "https://artificialanalysis.ai/models/glm-4.5" },
  { id: "glm-5", name: "GLM‑5 (Reasoning)", org: "Z.ai", releaseDate: "2026-02-12", access: "open", license: "MIT", modality: "text→text", totalParamsB: 744, activeParamsB: 40, contextK: 202.752, weightSizeGB: 1510, trainingTokensT: 28.5, aaIntelligence: 40, aaAgentic: null, outputTokensPerSecond: 51.9, blendedPricePerMTok: 0.66, primarySourceUrl: "https://z.ai/blog/glm-5?id=GLM5", aaUrl: "https://artificialanalysis.ai/models/glm-5" },
  { id: "glm-52-max", name: "GLM‑5.2 (max)", org: "Z.ai", releaseDate: "2026-06-16", access: "open", license: "MIT", modality: "text→text", totalParamsB: 753, activeParamsB: 40, contextK: 1000, weightSizeGB: 1506.7, trainingTokensT: null, aaIntelligence: 51.1, aaAgentic: 43.1, outputTokensPerSecond: 168.2, blendedPricePerMTok: 0.902, primarySourceUrl: "https://z.ai/blog/glm-5.2", aaUrl: "https://artificialanalysis.ai/models/glm-5-2" },

  { id: "grok-1", name: "Grok‑1", org: "xAI", releaseDate: "2024-03-17", access: "open", license: "Apache-2.0", modality: "text→text", totalParamsB: 314, activeParamsB: 78, contextK: 8.192, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 6.0, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://x.ai/news/grok-os", aaUrl: "https://artificialanalysis.ai/models/grok-1" },
  { id: "grok-3", name: "Grok 3", org: "xAI", releaseDate: "2025-02-17", access: "api", license: "Proprietary", modality: "text→text", totalParamsB: null, activeParamsB: null, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 18.4, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 3.876, primarySourceUrl: "https://x.ai/news/grok-3", aaUrl: "https://artificialanalysis.ai/models/grok-3" },
  { id: "grok-4", name: "Grok 4", org: "xAI", releaseDate: "2025-07-09", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 256, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 33.3, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 7.70, primarySourceUrl: "https://x.ai/news/grok-4", aaUrl: "https://artificialanalysis.ai/models/grok-4" },
  { id: "grok-45-high", name: "Grok 4.5 (high)", org: "SpaceXAI", releaseDate: "2026-07-08", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 500, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 53.8, aaAgentic: 45.7, outputTokensPerSecond: 90.1, blendedPricePerMTok: 1.35, primarySourceUrl: "https://x.ai/news/grok-4-5", aaUrl: "https://artificialanalysis.ai/models/grok-4-5" },

  { id: "qwen-72b-chat", name: "Qwen‑72B‑Chat", org: "Alibaba / Qwen", releaseDate: "2023-11-30", access: "open", license: "Tongyi Qianwen License Agreement", modality: "text→text", totalParamsB: 72, activeParamsB: 72, contextK: 32, weightSizeGB: 144.58, trainingTokensT: 3, aaIntelligence: 3, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://qwenlm.github.io/blog/qwen/", aaUrl: "https://artificialanalysis.ai/models/qwen-chat-72b" },
  { id: "qwen15-110b-chat", name: "Qwen1.5‑110B‑Chat", org: "Alibaba / Qwen", releaseDate: "2024-04-25", access: "open", license: "Tongyi Qianwen License Agreement", modality: "text→text", totalParamsB: 110, activeParamsB: 110, contextK: 32, weightSizeGB: 222.42, trainingTokensT: null, aaIntelligence: 4, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://qwenlm.github.io/blog/qwen1.5-110b/", aaUrl: "https://artificialanalysis.ai/models/qwen1.5-110b-chat" },
  { id: "qwen2-72b-instruct", name: "Qwen2‑72B‑Instruct", org: "Alibaba / Qwen", releaseDate: "2024-06-07", access: "open", license: "Tongyi Qianwen License Agreement", modality: "text→text", totalParamsB: 72.71, activeParamsB: 72.71, contextK: 128, weightSizeGB: 145.41, trainingTokensT: 7, aaIntelligence: 6, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://qwenlm.github.io/blog/qwen2/", aaUrl: "https://artificialanalysis.ai/models/qwen2-72b-instruct" },
  { id: "qwen25-72b-instruct", name: "Qwen2.5‑72B‑Instruct", org: "Alibaba / Qwen", releaseDate: "2024-09-19", access: "open", license: "Qwen License Agreement", modality: "text→text", totalParamsB: 72, activeParamsB: 72, contextK: 128, weightSizeGB: 145.41, trainingTokensT: 18, aaIntelligence: 10, aaAgentic: null, outputTokensPerSecond: 31.8, blendedPricePerMTok: 0.39, primarySourceUrl: "https://qwenlm.github.io/blog/qwen2.5/", aaUrl: "https://artificialanalysis.ai/models/qwen2-5-72b-instruct" },
  { id: "qwen3-235b-a22b", name: "Qwen3‑235B‑A22B", org: "Alibaba / Qwen", releaseDate: "2025-04-29", access: "open", license: "Apache-2.0", modality: "text→text", totalParamsB: 235, activeParamsB: 22, contextK: 128, weightSizeGB: 470.19, trainingTokensT: 36, aaIntelligence: 13, aaAgentic: null, outputTokensPerSecond: 59, blendedPricePerMTok: null, primarySourceUrl: "https://qwenlm.github.io/blog/qwen3/", aaUrl: "https://artificialanalysis.ai/models/qwen3-235b-a22b-instruct-reasoning" },
  { id: "qwen35-397b-a17b", name: "Qwen3.5‑397B‑A17B", org: "Alibaba / Qwen", releaseDate: "2026-02-16", access: "open", license: "Apache-2.0", modality: "text+image+video→text", totalParamsB: 397, activeParamsB: 17, contextK: 262.144, weightSizeGB: 806.80, trainingTokensT: null, aaIntelligence: 34, aaAgentic: 19.85, outputTokensPerSecond: 60.4, blendedPricePerMTok: 0.90, primarySourceUrl: "https://huggingface.co/Qwen/Qwen3.5-397B-A17B", aaUrl: "https://artificialanalysis.ai/models/qwen3-5-397b-a17b" },
  { id: "qwen36-35b-a3b", name: "Qwen3.6‑35B‑A3B", org: "Alibaba / Qwen", releaseDate: "2026-04-15", access: "open", license: "Apache-2.0", modality: "text+image+video→text", totalParamsB: 35, activeParamsB: 3, contextK: 262.144, weightSizeGB: 71.90, trainingTokensT: null, aaIntelligence: 32, aaAgentic: 21.4, outputTokensPerSecond: 133.7, blendedPricePerMTok: null, primarySourceUrl: "https://qwen.ai/blog?id=qwen3.6-35b-a3b", aaUrl: "https://artificialanalysis.ai/models/qwen3-6-35b-a3b/" },
  { id: "qwen37-max", name: "Qwen3.7‑Max", org: "Alibaba / Qwen", releaseDate: "2026-05-20", access: "api", license: "Proprietary", modality: "text+image→text", totalParamsB: null, activeParamsB: null, contextK: 1000, weightSizeGB: null, trainingTokensT: null, aaIntelligence: 46, aaAgentic: 30.6, outputTokensPerSecond: 204.1, blendedPricePerMTok: null, primarySourceUrl: "https://www.alibabagroup.com/en-US/document-1994119844504535040", aaUrl: "https://artificialanalysis.ai/models/qwen3-7-max/" },

  { id: "minimax-text-01", name: "MiniMax‑Text‑01", org: "MiniMax", releaseDate: "2025-01-15", access: "open", license: "MiniMax Model License", modality: "text→text", totalParamsB: 456, activeParamsB: 45.9, contextK: 4000, weightSizeGB: 914.67, trainingTokensT: 11.4, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://www.minimax.io/news/minimax-01-series-2", aaUrl: null },
  { id: "minimax-m1-80k", name: "MiniMax‑M1‑80k", org: "MiniMax", releaseDate: "2025-06-16", access: "open", license: "Apache-2.0", modality: "text→text", totalParamsB: 456, activeParamsB: 45.9, contextK: 1000, weightSizeGB: 912.212, trainingTokensT: 7.5, aaIntelligence: 17.67, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: 0.72, primarySourceUrl: "https://www.minimax.io/news/minimaxm1", aaUrl: "https://artificialanalysis.ai/models/minimax-m1-80k" },
  { id: "minimax-m2", name: "MiniMax‑M2", org: "MiniMax", releaseDate: "2025-10-27", access: "open", license: "Modified MIT", modality: "text→text", totalParamsB: 230, activeParamsB: 10, contextK: 196.608, weightSizeGB: 230.134, trainingTokensT: null, aaIntelligence: 28.31, aaAgentic: null, outputTokensPerSecond: 84.6, blendedPricePerMTok: 0.39, primarySourceUrl: "https://www.minimax.io/blog/minimax-m2-en-1748600000", aaUrl: "https://artificialanalysis.ai/models/minimax-m2" },
  { id: "minimax-m21", name: "MiniMax‑M2.1", org: "MiniMax", releaseDate: "2025-12-23", access: "open", license: "Modified MIT", modality: "text→text", totalParamsB: 230, activeParamsB: 10, contextK: 196.608, weightSizeGB: 230.134, trainingTokensT: null, aaIntelligence: 31.36, aaAgentic: null, outputTokensPerSecond: 81.1, blendedPricePerMTok: 0.39, primarySourceUrl: "https://www.minimax.io/news/minimax-m21", aaUrl: "https://artificialanalysis.ai/models/minimax-m2-1" },
  { id: "minimax-m25", name: "MiniMax‑M2.5", org: "MiniMax", releaseDate: "2026-02-12", access: "open", license: "MiniMax Model License (modified MIT tag)", modality: "text→text", totalParamsB: 230, activeParamsB: 10, contextK: 196.608, weightSizeGB: 230.134, trainingTokensT: 29.2, aaIntelligence: 33.65, aaAgentic: null, outputTokensPerSecond: 86.1, blendedPricePerMTok: 0.20, primarySourceUrl: "https://www.minimax.io/blog/minimax-m25", aaUrl: "https://artificialanalysis.ai/models/minimax-m2-5" },
  { id: "minimax-m3", name: "MiniMax‑M3", org: "MiniMax", releaseDate: "2026-06-01", access: "open", license: "MiniMax Community License", modality: "text+image+video→text", totalParamsB: 428, activeParamsB: 23, contextK: 1048.576, weightSizeGB: 854.176, trainingTokensT: null, aaIntelligence: 44.44, aaAgentic: 35.36, outputTokensPerSecond: 84.6, blendedPricePerMTok: 0.22, primarySourceUrl: "https://www.minimax.io/blog/minimax-m3", aaUrl: "https://artificialanalysis.ai/models/minimax-m3" },

  { id: "flux-1-dev", name: "FLUX.1 [dev]", org: "Black Forest Labs", releaseDate: "2024-08-01", access: "open", license: "FLUX.1 [dev] Non-Commercial License", modality: "text→image", totalParamsB: 12, activeParamsB: 12, contextK: null, weightSizeGB: 23.8, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/black-forest-labs/flux", aaUrl: "https://artificialanalysis.ai/image/leaderboard/text-to-image/open-weights" },
  { id: "hunyuanvideo", name: "HunyuanVideo", org: "Tencent Hunyuan", releaseDate: "2024-12-03", access: "open", license: "Tencent Hunyuan Community License", modality: "text→video", totalParamsB: 13, activeParamsB: 13, contextK: null, weightSizeGB: 26.6, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/Tencent-Hunyuan/HunyuanVideo", aaUrl: "https://artificialanalysis.ai/video/leaderboard/text-to-video/open-weights" },
  { id: "wan21-t2v-14b", name: "Wan2.1‑T2V‑14B", org: "Alibaba / Wan", releaseDate: "2025-02-22", access: "open", license: "Apache-2.0", modality: "text→video", totalParamsB: 14, activeParamsB: 14, contextK: null, weightSizeGB: 69.1, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/Wan-Video/Wan2.1", aaUrl: "https://artificialanalysis.ai/video/models/wan-2-1-14b" },
  { id: "qwen25-omni-7b", name: "Qwen2.5‑Omni‑7B", org: "Alibaba / Qwen", releaseDate: "2025-03-26", access: "open", license: "Apache-2.0", modality: "text+image+audio+video→text+audio", totalParamsB: 10.732, activeParamsB: 10.732, contextK: 32.768, weightSizeGB: 22.37, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/QwenLM/Qwen2.5-Omni", aaUrl: null },
  { id: "bagel-7b-mot", name: "BAGEL‑7B‑MoT", org: "ByteDance Seed", releaseDate: "2025-05-20", access: "open", license: "Apache-2.0", modality: "text+image+video→text+image", totalParamsB: 14, activeParamsB: 7, contextK: null, weightSizeGB: 29.6, trainingTokensT: 5.1776, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/ByteDance-Seed/Bagel", aaUrl: "https://artificialanalysis.ai/image/leaderboard/text-to-image/open-weights" },
  { id: "wan22-t2v-a14b", name: "Wan2.2‑T2V‑A14B", org: "Alibaba / Wan", releaseDate: "2025-07-28", access: "open", license: "Apache-2.0", modality: "text→video", totalParamsB: 27, activeParamsB: 14, contextK: null, weightSizeGB: 126.202, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/Wan-Video/Wan2.2", aaUrl: "https://artificialanalysis.ai/video/models/wan-2-2-a14b" },
  { id: "qwen-image-20b", name: "Qwen-Image", org: "Alibaba / Qwen", releaseDate: "2025-08-04", access: "open", license: "Apache-2.0", modality: "text→image", totalParamsB: 20, activeParamsB: 20, contextK: null, weightSizeGB: 57.699, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://qwenlm.github.io/blog/qwen-image/", aaUrl: "https://artificialanalysis.ai/image/leaderboard/text-to-image/open-weights" },
  { id: "z-image-turbo", name: "Z-Image-Turbo", org: "Alibaba / Tongyi-MAI", releaseDate: "2025-11-26", access: "open", license: "Apache-2.0", modality: "text→image", totalParamsB: 6.155, activeParamsB: 6.155, contextK: null, weightSizeGB: 32.832, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://github.com/Tongyi-MAI/Z-Image", aaUrl: "https://artificialanalysis.ai/image/models/alibaba_z-image-turbo" },
  { id: "ltx-23", name: "LTX‑2.3", org: "Lightricks / LTX", releaseDate: "2026-03-05", access: "open", license: "LTX-2 Community License", modality: "text→video", totalParamsB: 22, activeParamsB: 22, contextK: null, weightSizeGB: 46.1, trainingTokensT: null, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://huggingface.co/Lightricks/LTX-2.3", aaUrl: "https://artificialanalysis.ai/video/leaderboard/text-to-video/open-weights" },
  { id: "cosmos3-super", name: "Cosmos3‑Super Family", org: "NVIDIA", releaseDate: "2026-05-31", access: "open", license: "NVIDIA Open Model License", modality: "text+image→image+video", totalParamsB: 64, activeParamsB: 32, contextK: null, weightSizeGB: 133, trainingTokensT: 19.76, aaIntelligence: null, aaAgentic: null, outputTokensPerSecond: null, blendedPricePerMTok: null, primarySourceUrl: "https://huggingface.co/nvidia/Cosmos3-Super", aaUrl: "https://artificialanalysis.ai/image/leaderboard/text-to-image/open-weights" },
];
