import type {
  Fact,
  ModelTechnologyLink,
  PrimaryContributor,
  Source,
  TechnologyCategory,
  TechnologyComparison,
  TimelineEvent,
  TimelineLane,
} from "./types";

const ACCESSED_AT = "2026-07-19";

function source(
  id: string,
  title: string,
  publisher: string,
  url: string,
  type: Source["type"],
): Source {
  return { id, title, publisher, url, type, accessedAt: ACCESSED_AT };
}

function fact(label: string, value: string, sourceIds: string[], method?: string): Fact {
  return { label, value, sourceIds, status: "已披露", method };
}

interface TechnologyInput {
  id: string;
  date: string;
  title: string;
  organization: string;
  category: TechnologyCategory;
  eyebrow: string;
  summary: string;
  score: string;
  tags: string[];
  situation: string;
  target: string;
  action: string;
  result: string;
  mechanism: string;
  bestFor: string;
  experiment: string;
  computeMemory: string;
  parallelism: string;
  limitations: string;
  availability: string;
  sources: Source[];
  breakthroughs?: string[];
  tier?: TimelineEvent["tier"];
}

const contributorByTechnology: Record<string, PrimaryContributor> = {
  "tech-full-attention": { name: "Ashish Vaswani", role: "first-author", organization: "Google Brain / Google Research", sourceUrl: "https://arxiv.org/abs/1706.03762", profileLabel: "论文作者页", profileUrl: "https://arxiv.org/abs/1706.03762", note: "论文公开作者与机构；未以不可靠同名结果冒充个人主页。" },
  "tech-switch-transformer": { name: "William Fedus", role: "first-author", organization: "Google Research", sourceUrl: "https://arxiv.org/abs/2101.03961", profileLabel: "论文作者页", profileUrl: "https://arxiv.org/abs/2101.03961" },
  "tech-expert-choice": { name: "Yanqi Zhou", role: "first-author", organization: "Google Research", sourceUrl: "https://arxiv.org/abs/2202.09368", profileLabel: "个人主页", profileUrl: "https://zhouyanqi.github.io/" },
  "tech-paged-attention": { name: "Woosuk Kwon", role: "first-author", organization: "UC Berkeley", sourceUrl: "https://arxiv.org/abs/2309.06180", profileLabel: "个人主页", profileUrl: "https://woosuk.me/" },
  "tech-loss-free-balancing": { name: "Lean Wang", role: "first-author", organization: "Peking University / DeepSeek-AI", sourceUrl: "https://arxiv.org/abs/2408.15664", profileLabel: "个人主页", profileUrl: "https://leanwang326.github.io/.github.io/" },
  "tech-gated-deltanet": { name: "Songlin Yang", role: "first-author", organization: "NVIDIA Research", sourceUrl: "https://arxiv.org/abs/2412.06464", profileLabel: "个人主页", profileUrl: "https://sustcsonglin.github.io/" },
  "tech-muon": { name: "Jingyuan Liu", role: "first-author", organization: "Moonshot AI", sourceUrl: "https://arxiv.org/abs/2502.16982", profileLabel: "论文作者页", profileUrl: "https://arxiv.org/abs/2502.16982", note: "此处一作对应 Muon 可扩展训练论文；Muon 原始实现由 Keller Jordan 发布。" },
  "tech-grpo": { name: "Zhihong Shao", role: "first-author", organization: "DeepSeek-AI", sourceUrl: "https://arxiv.org/abs/2402.03300", profileLabel: "个人主页", profileUrl: "https://zhihongshao.github.io/" },
  "tech-dancegrpo": { name: "Zeyue Xue", role: "first-author", organization: "ByteDance Seed / The University of Hong Kong", sourceUrl: "https://arxiv.org/abs/2505.07818", profileLabel: "GitHub", profileUrl: "https://github.com/XueZeyue" },
  "tech-diffusionnft": { name: "Kaiwen Zheng", role: "first-author", organization: "Tsinghua University / NVIDIA", sourceUrl: "https://arxiv.org/abs/2506.01347", profileLabel: "个人主页", profileUrl: "https://zhengkw18.github.io/" },
  "tech-opd": { name: "Kevin Lu", role: "first-author", organization: "Thinking Machines Lab", sourceUrl: "https://thinkingmachines.ai/blog/on-policy-distillation/", profileLabel: "个人主页", profileUrl: "https://kevinlu.ai/" },
  "tech-triton": { name: "Philippe Tillet", role: "first-author", organization: "OpenAI", sourceUrl: "https://openai.com/index/triton/", profileLabel: "GitHub", profileUrl: "https://github.com/ptillet" },
  "tech-ascend-c": { name: "Huawei Ascend C 团队", role: "project-team", organization: "Huawei", sourceUrl: "https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1alpha002/API/ascendcopapi/atlasascendc_api_07_0003.html", profileLabel: "官方项目", profileUrl: "https://www.hiascend.com/", note: "官方文档未列论文式个人一作，因此按主责团队标注。" },
  "tech-liger-kernel": { name: "Pin-Lun Hsu", role: "first-author", organization: "LinkedIn", sourceUrl: "https://arxiv.org/abs/2410.10989", profileLabel: "GitHub", profileUrl: "https://github.com/linkedin/Liger-Kernel" },
  "tech-triton-ascend": { name: "Triton-Ascend 维护团队", role: "project-team", organization: "Huawei Ascend / Triton 社区", sourceUrl: "https://github.com/Ascend/triton-ascend", profileLabel: "官方项目", profileUrl: "https://github.com/Ascend/triton-ascend", note: "开源仓未声明论文式个人一作。" },
  "tech-megakernel": { name: "Benjamin Spector", role: "first-author", organization: "Stanford Hazy Research", sourceUrl: "https://hazyresearch.stanford.edu/blog/2025-05-27-no-bubbles", profileLabel: "论文作者页", profileUrl: "https://hazyresearch.stanford.edu/blog/2025-05-27-no-bubbles" },
  "tech-megatron-lm": { name: "Mohammad Shoeybi", role: "first-author", organization: "NVIDIA", sourceUrl: "https://arxiv.org/abs/1909.08053", profileLabel: "论文作者页", profileUrl: "https://arxiv.org/abs/1909.08053" },
  "tech-deepspeed-zero": { name: "Samyam Rajbhandari", role: "first-author", organization: "Microsoft Research", sourceUrl: "https://arxiv.org/abs/1910.02054", profileLabel: "GitHub", profileUrl: "https://github.com/samyam" },
  "tech-fsdp1": { name: "Yanli Zhao", role: "first-author", organization: "Meta AI", sourceUrl: "https://arxiv.org/abs/2304.11277", profileLabel: "GitHub", profileUrl: "https://github.com/zhaojuanmao" },
  "tech-fsdp2": { name: "PyTorch Distributed 团队", role: "project-team", organization: "Meta / PyTorch", sourceUrl: "https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/", profileLabel: "官方项目", profileUrl: "https://github.com/pytorch/pytorch", note: "FSDP2 是 API / 实现迭代，官方发布未声明独立论文一作。" },
  "tech-deepep": { name: "DeepSeek-AI 开源基础设施团队", role: "project-team", organization: "DeepSeek-AI", sourceUrl: "https://github.com/deepseek-ai/DeepEP", profileLabel: "官方项目", profileUrl: "https://github.com/deepseek-ai/DeepEP", note: "仓库未声明论文式个人一作。" },
  "tech-vescale-fsdp": { name: "Zezhou Wang", role: "first-author", organization: "ByteDance Seed", sourceUrl: "https://arxiv.org/abs/2602.22437", profileLabel: "论文作者页", profileUrl: "https://arxiv.org/abs/2602.22437" },
};

const modelLinksByTechnology: Record<string, ModelTechnologyLink[]> = {
  "tech-full-attention": [
    { modelId: "deepseek-v3-2024-12", relation: "技术谱系", note: "Transformer 注意力基线；不表示仍采用原始 full attention 配置。" },
    { modelId: "qwen3-235b-a22b", relation: "技术谱系" },
    { modelId: "flux-1-dev", relation: "技术谱系" },
    { modelId: "hunyuanvideo-2024-12", relation: "技术谱系" },
  ],
  "tech-switch-transformer": [{ modelId: "qwen3-235b-a22b", relation: "技术谱系", note: "稀疏 MoE 路由谱系；模型并非原样使用 Switch top-1。" }],
  "tech-expert-choice": [{ modelId: "qwen3-235b-a22b", relation: "技术谱系", note: "作为专家路由对照谱系，不主张产品采用。" }],
  "tech-paged-attention": [{ modelId: "gpt-oss-120b", relation: "训练 / 推理支撑" }, { modelId: "deepseek-v3-2024-12", relation: "训练 / 推理支撑" }],
  "tech-loss-free-balancing": [{ modelId: "deepseek-v3-2024-12", relation: "采用" }, { modelId: "deepseek-v4-pro", relation: "技术谱系" }],
  "tech-gated-deltanet": [{ modelId: "qwen3-5-397b-a17b", relation: "采用" }, { modelId: "qwen3-6-35b-a3b", relation: "技术谱系" }],
  "tech-muon": [{ modelId: "kimi-k2", relation: "采用" }, { modelId: "kimi-k2-5", relation: "采用" }, { modelId: "kimi-k2-6", relation: "技术谱系" }, { modelId: "kimi-k3", relation: "技术谱系" }],
  "tech-grpo": [{ modelId: "deepseek-v3-2024-12", relation: "技术谱系" }, { modelId: "qwen3-235b-a22b", relation: "训练 / 推理支撑" }],
  "tech-dancegrpo": [{ modelId: "flux-1-dev", relation: "基础模型" }, { modelId: "hunyuanvideo-2024-12", relation: "实验验证" }],
  "tech-diffusionnft": [{ modelId: "flux-1-dev", relation: "实验验证", note: "链接表示扩散模型实验语境，不声称 FLUX 产品采用。" }],
  "tech-opd": [{ modelId: "qwen3-235b-a22b", relation: "技术谱系" }],
  "tech-triton": [{ modelId: "deepseek-v3-2024-12", relation: "训练 / 推理支撑" }, { modelId: "gpt-oss-120b", relation: "训练 / 推理支撑" }],
  "tech-ascend-c": [{ modelId: "qwen3-235b-a22b", relation: "训练 / 推理支撑", note: "昇腾部署能力关联，不主张其官方训练硬件。" }],
  "tech-liger-kernel": [{ modelId: "qwen3-235b-a22b", relation: "训练 / 推理支撑" }],
  "tech-triton-ascend": [{ modelId: "qwen3-235b-a22b", relation: "训练 / 推理支撑" }],
  "tech-megakernel": [{ modelId: "gpt-oss-120b", relation: "实验验证" }],
  "tech-megatron-lm": [{ modelId: "deepseek-v3-2024-12", relation: "技术谱系" }, { modelId: "qwen3-235b-a22b", relation: "训练 / 推理支撑" }],
  "tech-deepspeed-zero": [{ modelId: "qwen3-235b-a22b", relation: "训练 / 推理支撑" }],
  "tech-fsdp1": [{ modelId: "flux-1-dev", relation: "训练 / 推理支撑" }],
  "tech-fsdp2": [{ modelId: "qwen-image-20b", relation: "训练 / 推理支撑" }],
  "tech-deepep": [{ modelId: "deepseek-v3-2024-12", relation: "采用" }, { modelId: "deepseek-v4-pro", relation: "技术谱系" }],
  "tech-vescale-fsdp": [{ modelId: "qwen3-5-397b-a17b", relation: "实验验证" }],
};

function technology(input: TechnologyInput): TimelineEvent {
  const sourceIds = input.sources.map((item) => item.id);
  const comparison: TechnologyComparison = {
    category: input.category,
    mechanism: input.mechanism,
    bestFor: input.bestFor,
    experiment: input.experiment,
    result: input.result,
    computeMemory: input.computeMemory,
    parallelism: input.parallelism,
    limitations: input.limitations,
    availability: input.availability,
  };

  return {
    id: input.id,
    date: input.date,
    title: input.title,
    organization: input.organization,
    eyebrow: input.eyebrow,
    summary: input.summary,
    confidence: "高",
    score: input.score,
    tags: [...input.tags, input.category, "STAR"],
    tier: input.tier ?? "baseline",
    star: {
      situation: input.situation,
      target: input.target,
      action: input.action,
      result: input.result,
    },
    comparison,
    eventKind: "technology",
    primaryContributor: contributorByTechnology[input.id],
    modelLinks: modelLinksByTechnology[input.id] ?? [],
    breakthroughs: input.breakthroughs,
    facts: [
      fact("Situation / 动机", input.situation, sourceIds),
      fact("Target / 目标", input.target, sourceIds),
      fact("Action / 实验流程", input.action, sourceIds),
      fact("Result / 实验结果", input.result, sourceIds),
      fact("核心机制", input.mechanism, sourceIds),
      fact("适用场景", input.bestFor, sourceIds),
      fact("实验口径", input.experiment, sourceIds),
      fact("计算 / 显存", input.computeMemory, sourceIds),
      fact("并行维度", input.parallelism, sourceIds),
      fact("局限 / 适用边界", input.limitations, sourceIds),
      fact("代码 / 可用性", input.availability, sourceIds),
    ],
    sources: input.sources,
  };
}

const fullAttention = technology({
  id: "tech-full-attention",
  date: "2017-06-12",
  title: "Full Attention / Transformer",
  organization: "Google Brain / Google Research",
  category: "模型结构",
  eyebrow: "论文 / Attention",
  summary: "用全局多头自注意力替代循环与卷积，建立可并行训练的 Transformer 基线；代价是序列长度上的二次复杂度。",
  score: "28.4 BLEU",
  tags: ["Full Attention", "Transformer", "MHA"],
  situation: "主流序列到序列模型依赖 RNN/CNN，长距离依赖路径长且训练难以充分并行。",
  target: "仅用注意力完成序列建模，在不牺牲翻译质量的前提下缩短训练时间。",
  action: "构建编码器—解码器 Transformer，以 multi-head self-attention、位置编码和前馈层组成；在 WMT 2014 英德、英法翻译上训练评测。",
  result: "英德任务达到 28.4 BLEU；英法单模型达到 41.8 BLEU，并在 8 张 GPU 上训练 3.5 天。",
  mechanism: "每个 token 对序列中全部 token 做 softmax attention；多头并行学习不同关系。",
  bestFor: "中短上下文、追求质量上限和成熟 kernel 支持的训练与推理。",
  experiment: "WMT 2014 En-De / En-Fr；论文同时比较质量、训练成本与解析任务迁移。",
  computeMemory: "attention 计算与显存随序列长度 O(n²) 增长。",
  parallelism: "序列位置可并行；天然适合数据、张量与流水线并行。",
  limitations: "长上下文成本高；这里的结果来自机器翻译，不能直接外推到现代 LLM。",
  availability: "论文公开；主流框架均有实现。",
  breakthroughs: ["去除 recurrence / convolution", "multi-head self-attention", "位置编码支持序列顺序"],
  sources: [source("full-attention-paper", "Attention Is All You Need", "NeurIPS", "https://arxiv.org/abs/1706.03762", "论文")],
});

const switchTransformer = technology({
  id: "tech-switch-transformer",
  date: "2021-01-11",
  title: "Switch Transformer / 辅助损失均衡",
  organization: "Google Research",
  category: "模型结构",
  eyebrow: "论文 / MoE Load Balancing",
  summary: "以 top-1 token-choice router 和辅助负载均衡损失简化稀疏 MoE，让参数容量增长而单 token 计算近似不变。",
  score: "up to 7×",
  tags: ["MoE", "Switch", "Aux Loss", "Top-1 Routing"],
  situation: "稠密模型扩参会同步增加每个 token 的计算；早期 MoE 又受通信、路由不均和低精度不稳定限制。",
  target: "把 MoE 简化到可稳定扩至万亿参数，并维持接近固定的单 token 计算量。",
  action: "每个 token 只路由到一个专家，以 capacity factor 限流并用 auxiliary loss 鼓励专家负载均衡；在 T5 系列与 C4 上比较稠密基线。",
  result: "同等资源下预训练速度最高提升 7×；万亿参数模型相对 T5-XXL 报告 4× 加速。",
  mechanism: "token-choice top-1 路由 + 专家容量上限 + 可微辅助均衡损失。",
  bestFor: "需要以稀疏激活扩大参数容量、且可接受 all-to-all 通信的预训练。",
  experiment: "T5-Base/Large/XXL 与 Switch 变体；C4 预训练及 101 语言多语任务。",
  computeMemory: "激活 FLOPs 近似稠密基线，但总权重、通信与专家参数显存显著增加。",
  parallelism: "专家并行 + 数据并行；需处理跨设备 token dispatch/combine。",
  limitations: "辅助损失会向主目标注入梯度；容量不足会丢 token，专家并行依赖网络。",
  availability: "论文与 JMLR 版本公开；Transformers 等框架有实现。",
  breakthroughs: ["top-1 routing", "capacity factor", "辅助损失控制专家负载"],
  sources: [source("switch-paper", "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity", "Google Research / JMLR", "https://arxiv.org/abs/2101.03961", "论文")],
});

const expertChoice = technology({
  id: "tech-expert-choice",
  date: "2022-02-18",
  title: "Expert Choice Routing",
  organization: "Google Research",
  category: "模型结构",
  eyebrow: "论文 / MoE Load Balancing",
  summary: "把“token 选专家”反转为“专家选 token”，用固定 bucket 从结构上保证每个专家负载一致。",
  score: ">2× 收敛",
  tags: ["MoE", "Expert Choice", "Load Balance"],
  situation: "token-choice top-k 会产生专家过载、欠载与 token 丢弃，也可能让部分专家训练不足。",
  target: "在允许 token 获得不同计算量的同时，让每个专家获得固定、可预测的负载。",
  action: "每个专家从全局 token 中选择自己的 top-k，设置固定 bucket size；以相同算力与 Switch top-1、GShard top-2 比较预训练收敛与下游迁移。",
  result: "相同计算资源下收敛时间改善超过 2×；在 11 个 GLUE/SuperGLUE 任务上均优于对照路由。",
  mechanism: "expert-choice：专家固定容量选 token，单 token 可被 0 到多个专家接收。",
  bestFor: "需要严格专家负载可预测、愿意接受每 token 计算不均的 MoE 训练。",
  experiment: "与 Switch top-1、GShard top-2 在相同计算资源下做预训练与 11 项下游评测。",
  computeMemory: "专家负载固定，减少过配 capacity；token 侧计算量不固定。",
  parallelism: "专家并行更易做静态容量规划。",
  limitations: "token 可能未被任何专家选中，或被多个专家选中；不保证每 token 固定 FLOPs。",
  availability: "论文与 Google Research 说明公开。",
  breakthroughs: ["专家反向选择 token", "固定 bucket 实现结构性均衡"],
  sources: [
    source("expert-choice-paper", "Mixture-of-Experts with Expert Choice Routing", "NeurIPS", "https://arxiv.org/abs/2202.09368", "论文"),
    source("expert-choice-blog", "Mixture-of-Experts with Expert Choice Routing", "Google Research", "https://research.google/blog/mixture-of-experts-with-expert-choice-routing/", "官方博客"),
  ],
});

const pagedAttention = technology({
  id: "tech-paged-attention",
  date: "2023-09-12",
  title: "PagedAttention / vLLM",
  organization: "UC Berkeley / Stanford / UCSD",
  category: "模型结构",
  eyebrow: "论文 / Attention Memory",
  summary: "借鉴操作系统分页管理 KV cache，消除连续预留造成的碎片，是推理内存管理创新而非训练 attention 结构。",
  score: "2–4× 吞吐",
  tags: ["PagedAttention", "vLLM", "KV Cache", "Serving"],
  situation: "自回归服务的 KV cache 动态增长且长度未知，连续内存预留造成碎片和重复拷贝，限制可并发 batch。",
  target: "把 KV cache 浪费降至接近零，并在相同延迟目标下提高请求吞吐。",
  action: "将 KV cache 切为固定大小物理块并用逻辑页表映射；在 vLLM 中实现共享、调度与抢占，对比 FasterTransformer 和 Orca。",
  result: "在相同延迟水平下，代表性 LLM 服务吞吐提升 2–4×；长序列、大模型和复杂解码收益更明显。",
  mechanism: "逻辑连续、物理离散的 block table；attention kernel 按页读取 KV cache。",
  bestFor: "在线自回归 LLM 推理、连续批处理、beam / parallel sampling。",
  experiment: "多模型、多长度与多种解码算法下的服务吞吐/延迟评测。",
  computeMemory: "减少 KV cache 碎片与复制；不改变 full attention 的理论计算复杂度。",
  parallelism: "服务级 batching 与多请求共享；不是训练并行方案。",
  limitations: "需要分页感知 kernel；引入地址转换和实现复杂度，且论文结论不代表训练加速。",
  availability: "论文公开；vLLM 开源并广泛部署。",
  breakthroughs: ["KV cache 分页", "跨请求共享物理块", "内存管理与调度协同设计"],
  sources: [
    source("paged-paper", "Efficient Memory Management for Large Language Model Serving with PagedAttention", "SOSP", "https://arxiv.org/abs/2309.06180", "论文"),
    source("paged-repo", "vLLM", "vLLM Project", "https://github.com/vllm-project/vllm", "代码仓"),
  ],
});

const lossFreeBalancing = technology({
  id: "tech-loss-free-balancing",
  date: "2024-08-28",
  title: "Auxiliary-Loss-Free MoE Balancing",
  organization: "DeepSeek-AI",
  category: "模型结构",
  eyebrow: "论文 / MoE Load Balancing",
  summary: "在路由分数上动态加入专家偏置，用反馈控制均衡负载，不再让均衡目标的梯度干扰语言建模目标。",
  score: "3B / 200B tokens",
  tags: ["MoE", "Aux-Loss-Free", "DeepSeek", "Routing Bias"],
  situation: "MoE 辅助均衡损失太弱会路由塌缩，太强又会以干扰梯度损害主任务性能。",
  target: "不向主损失注入均衡梯度，仍持续维持专家负载均衡。",
  action: "在 top-k 前为每个专家路由分数加可更新 bias；根据最近负载增减 bias，并在最高 3B 参数、200B token 的 MoE 上与辅助损失方案比较。",
  result: "论文在全部测试规模上同时报告更好的模型性能和负载均衡；摘要未提供可统一引用的单一提升百分比。",
  mechanism: "基于近期负载的 expert-wise bias feedback，不参与主模型梯度。",
  bestFor: "大规模 token-choice MoE，尤其关注主任务质量与负载控制解耦的训练。",
  experiment: "MoE 最大 3B 参数、训练数据最大 200B token；对比传统 auxiliary-loss-controlled balancing。",
  computeMemory: "增加轻量 bias 统计与更新；主要收益是降低过载和专家容量浪费。",
  parallelism: "服务于专家并行中的均匀 dispatch；不替代 all-to-all 通信实现。",
  limitations: "bias 更新率等超参仍需调节；论文实验规模小于后续超大 MoE。",
  availability: "论文公开；已在 DeepSeek-V3 技术报告中用于大规模训练。",
  breakthroughs: ["负载反馈与主梯度解耦", "expert-wise routing bias"],
  sources: [source("loss-free-paper", "Auxiliary-Loss-Free Load Balancing Strategy for Mixture-of-Experts", "DeepSeek-AI", "https://arxiv.org/abs/2408.15664", "论文")],
});

const gatedDeltaNet = technology({
  id: "tech-gated-deltanet",
  date: "2024-12-09",
  title: "Gated DeltaNet (GDN)",
  organization: "NVIDIA Research",
  category: "模型结构",
  eyebrow: "论文 / Linear Attention",
  summary: "把门控遗忘与 delta rule 精确更新结合，在固定大小状态上改善线性 attention 的检索与长上下文能力。",
  score: "ICLR 2025",
  tags: ["Gated DeltaNet", "GDN", "Linear Attention", "Delta Rule"],
  situation: "线性 attention 虽可用固定状态降低长序列成本，但在关联检索和长上下文上常落后于 softmax attention。",
  target: "保留线性递归状态的训练/解码效率，同时增强快速遗忘与定点写入能力。",
  action: "组合 data-dependent gate 与 delta update，推导硬件友好的并行训练算法；与 Mamba2、DeltaNet 在语言建模、常识、检索、长度外推和长上下文上比较。",
  result: "论文报告在多项任务上持续超过 Mamba2 与 DeltaNet；混合 GDN + sliding-window attention 进一步兼顾效率与质量。",
  mechanism: "固定大小 fast-weight state；gate 控制擦除，delta rule 根据当前读取误差进行局部更新。",
  bestFor: "长上下文、流式解码，以及需要线性序列复杂度的 hybrid 架构。",
  experiment: "纯 GDN 与 hybrid 变体；多规模语言模型和检索/外推基准。",
  computeMemory: "序列混合近线性；递归解码状态为常数大小。",
  parallelism: "提供 chunkwise parallel training；可与局部/full attention 层混排。",
  limitations: "固定状态会压缩历史；复杂检索仍可能需要 hybrid attention，生态成熟度低于 full attention。",
  availability: "论文与 NVIDIA 官方 PyTorch 实现已公开。",
  breakthroughs: ["gating + delta rule", "chunkwise 并行训练", "与 sliding-window attention 混合"],
  sources: [
    source("gdn-paper", "Gated Delta Networks: Improving Mamba2 with Delta Rule", "NVIDIA Research / ICLR", "https://arxiv.org/abs/2412.06464", "论文"),
    source("gdn-repo", "GatedDeltaNet", "NVIDIA Research", "https://github.com/NVlabs/GatedDeltaNet", "代码仓"),
  ],
});

const muon = technology({
  id: "tech-muon",
  date: "2025-02-24",
  title: "Muon Optimizer at Scale",
  organization: "Moonshot AI",
  category: "模型结构",
  eyebrow: "论文 / Optimizer",
  summary: "对二维权重更新做矩阵正交化，并用 weight decay 与参数尺度校准把 Muon 从小模型扩展到大规模 LLM。",
  score: "~2× compute efficiency",
  tags: ["Muon", "Optimizer", "Orthogonalization", "Moonlight"],
  situation: "Muon 在小模型上优于 AdamW，但大模型可扩展性、更新尺度、通信与权重衰减尚未验证。",
  target: "让 Muon 可直接用于大规模语言模型，并验证相对 AdamW 的计算效率。",
  action: "加入 weight decay 和 per-parameter update-scale 校准；做 compute-optimal scaling-law 实验，并用分布式 Muon 训练 3B/16B MoE Moonlight，数据量 5.7T token。",
  result: "scaling-law 实验报告相对 AdamW 约 2× 计算效率；Moonlight 在更少训练 FLOPs 下推进当时 Pareto 前沿。",
  mechanism: "Newton–Schulz 等近似正交化二维更新；非二维参数通常仍由 AdamW 类方法处理。",
  bestFor: "预训练中的矩阵权重；愿意承担额外正交化与分布式通信实现复杂度的团队。",
  experiment: "多规模 scaling law + 3B/16B MoE、5.7T token 端到端训练。",
  computeMemory: "论文实现做 memory-optimal、communication-efficient 分布式 Muon；优化器状态/通信口径与 AdamW 不同。",
  parallelism: "需在参数分片边界上保持矩阵结构，和普通逐元素 FSDP 存在组合挑战。",
  limitations: "并非所有参数都用 Muon；2× 是论文 scaling-law 口径，不能直接当作 wall-clock 2×。",
  availability: "论文、分布式实现与 Moonlight checkpoints 公开。",
  breakthroughs: ["矩阵正交化更新", "大模型 update-scale 校准", "分布式 Muon"],
  sources: [
    source("muon-paper", "Muon is Scalable for LLM Training", "Moonshot AI", "https://arxiv.org/abs/2502.16982", "论文"),
    source("muon-repo", "Moonlight", "Moonshot AI", "https://github.com/MoonshotAI/Moonlight", "代码仓"),
  ],
});

const grpo = technology({
  id: "tech-grpo",
  date: "2024-02-05",
  title: "GRPO",
  organization: "DeepSeek-AI",
  category: "算法流程",
  eyebrow: "论文 / Reinforcement Learning",
  summary: "用同题多次采样的组内相对奖励替代 PPO 的独立 critic，降低推理强化学习的显存与系统复杂度。",
  score: "MATH 51.7%",
  tags: ["GRPO", "RLVR", "DeepSeekMath", "PPO"],
  situation: "数学推理需要 RL 提升，但 PPO 额外训练 value/critic 模型，增加显存、计算和工程复杂度。",
  target: "保留 PPO 的稳定更新，同时用组内相对基线去掉 critic。",
  action: "对每个 prompt 采样一组回答，以组内奖励均值/方差归一化得到优势，配合 clipped policy objective；在 DeepSeekMath 7B 后训练。",
  result: "DeepSeekMath 7B 在 MATH 达 51.7%，64 样本 self-consistency 达 60.9%；成绩也受 120B 数学 token 继续预训练影响，不能归因于 GRPO 单项。",
  mechanism: "group-relative advantage + PPO-style clipping + KL regularization，无独立 value model。",
  bestFor: "有可验证终局奖励的数学、代码、工具使用等 reasoning 后训练。",
  experiment: "DeepSeek-Coder-Base-v1.5 7B 继续预训练 120B 数学相关 token，再做 SFT/RL 并评测 MATH。",
  computeMemory: "省去 critic 参数与状态；rollout 采样仍是主要成本。",
  parallelism: "rollout / inference 与训练 worker 可分离扩展；group samples 可并行。",
  limitations: "相对优势依赖同组奖励差异；结果奖励稀疏，易受 reward hacking 与长度偏置影响。",
  availability: "论文公开；多个开源 RL 框架已实现。",
  breakthroughs: ["组内相对优势", "去掉 PPO critic", "面向可验证奖励的推理后训练"],
  sources: [source("grpo-paper", "DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models", "DeepSeek-AI", "https://arxiv.org/abs/2402.03300", "论文")],
});

const danceGrpo = technology({
  id: "tech-dancegrpo",
  date: "2025-05-12",
  title: "DanceGRPO",
  organization: "ByteDance Seed / 香港大学",
  category: "算法流程",
  eyebrow: "论文 / Visual RL",
  summary: "把 GRPO 扩展到 diffusion 与 rectified flow 的图像/视频生成，在多任务、多奖励模型上统一视觉 RL。",
  score: "up to +181%",
  tags: ["DanceGRPO", "Visual RL", "Diffusion", "Rectified Flow"],
  situation: "DDPO、DPOK 等视觉 RL 在大规模多样 prompt、ODE sampler 与视频任务上容易不稳定或不兼容。",
  target: "用统一 GRPO 框架覆盖 diffusion/flow、图像/视频与多种黑盒奖励。",
  action: "在 Stable Diffusion、FLUX、HunyuanVideo、SkyReel-I2V 上，覆盖 T2I/T2V/I2V 与五类 reward model；在 HPS、CLIP、VideoAlign、GenEval 上比较。",
  result: "跨基准相对 baseline 最高提升 181%，并在复杂视频生成和稀疏二值奖励下保持稳定优化。",
  mechanism: "把生成轨迹视作 policy rollout，使用组相对优势与适配连续生成过程的 likelihood/更新设计。",
  bestFor: "需要用审美、对齐、运动或二值偏好奖励优化图像/视频生成模型。",
  experiment: "2 类生成范式、3 类任务、4 个基础模型、5 类 reward model。",
  computeMemory: "需反向传播生成轨迹并多次采样；稳定性优于论文对照，但成本仍高。",
  parallelism: "prompt/group rollout 可并行；视频轨迹使显存与通信压力更大。",
  limitations: "181% 是跨实验的最高相对值，不代表每个模型/指标；奖励模型偏差仍会传递。",
  availability: "论文与项目页公开。",
  breakthroughs: ["GRPO 统一视觉生成 RL", "覆盖 diffusion 与 rectified flow", "首次系统扩到视频生成"],
  sources: [source("dancegrpo-paper", "DanceGRPO: Unleashing GRPO on Visual Generation", "HKU / Shanghai AI Lab", "https://arxiv.org/abs/2505.07818", "论文")],
});

const diffusionNft = technology({
  id: "tech-diffusionnft",
  date: "2025-09-19",
  title: "DiffusionNFT",
  organization: "NVIDIA / Stanford / Tsinghua",
  category: "算法流程",
  eyebrow: "论文 / Diffusion RL",
  summary: "不在反向采样轨迹上估 likelihood，而是在 forward process 上对比正负样本，把黑盒奖励转成 flow-matching 微调方向。",
  score: "up to 25×",
  tags: ["DiffusionNFT", "Flow Matching", "Online RL", "CFG-free"],
  situation: "对 diffusion 做在线 RL 往往需离散反向过程、估计 likelihood，并受 solver、forward/reverse 不一致和 CFG 集成限制。",
  target: "在无需轨迹 likelihood 的情况下支持任意黑盒 solver，并提升视觉在线 RL 的训练效率。",
  action: "按奖励把在线生成分为正/负样本，在 forward flow-matching 目标中做 negative-aware 对比；与 FlowGRPO 头对头并在 SD3.5-Medium 上多奖励评测。",
  result: "相对 FlowGRPO 最高 25× 训练效率；GenEval 在 1k step 从 0.24 升至 0.98，FlowGRPO 超过 5k step 加 CFG 达 0.95。",
  mechanism: "forward-process Diffusion Negative-aware FineTuning；仅需 clean images，不需保存反向采样轨迹。",
  bestFor: "使用 flow matching/diffusion、黑盒 sampler 与多 reward model 的图像生成对齐。",
  experiment: "SD3.5-Medium；与 FlowGRPO 同口径比较训练步数、CFG 与 GenEval，并评测多奖励模型。",
  computeMemory: "省去轨迹存储与 likelihood 估计，支持 CFG-free；效率数字依论文设定。",
  parallelism: "在线样本生成可并行，训练阶段退化为常规 flow-matching 式监督目标。",
  limitations: "2025 提出且实验集中图像生成；正负样本划分质量依赖奖励模型。",
  availability: "ICLR 2026 Oral 论文公开；代码可用性以论文项目更新为准。",
  breakthroughs: ["forward-process online RL", "negative-aware 正负对比", "任意 black-box solver"],
  sources: [source("diffusionnft-paper", "DiffusionNFT: Online Diffusion Reinforcement with Forward Process", "NVIDIA / Stanford / Tsinghua", "https://arxiv.org/abs/2509.16117", "论文")],
});

const opd = technology({
  id: "tech-opd",
  date: "2025-10-27",
  title: "On-Policy Distillation (OPD)",
  organization: "Thinking Machines Lab",
  category: "算法流程",
  eyebrow: "官方博客 / Dense On-Policy Signal",
  summary: "让 student 生成自己的轨迹，再由 teacher 为每个 token 提供 dense reverse-KL 信号，结合 RL 的 on-policy relevance 与蒸馏的稠密监督。",
  score: "9–30× CE",
  tags: ["OPD", "Distillation", "Reverse KL", "Reasoning"],
  situation: "离线 SFT 会产生 distribution shift，传统 RL 只有 episode 级稀疏奖励，长推理的样本效率低。",
  target: "在 student 自己会访问的状态上，用 teacher 的逐 token 概率提供稠密学习信号。",
  action: "student 做 group rollout，teacher 对 student token 计算 logprob，以负 reverse KL 作逐 token advantage，再走 importance-sampling RL update；在 Qwen3 数学推理上复现。",
  result: "从 400k SFT 的 60% AIME'24 起，约 150 step / 77k prompts 达 70%；相对外推的 SFT-2M，计算效率约 9–30×。匹配架构实验报告 7–10× 更少梯度步、50–100× 计算效率。",
  mechanism: "student on-policy trajectory + teacher token logprob + reverse-KL advantage。",
  bestFor: "已有强 teacher、student 已具备目标行为 support 的 reasoning、个性化与持续学习。",
  experiment: "Qwen3-8B-Base/8B/32B，OpenThoughts-3 初始化与 DeepMath rollout；比较 SFT、RL 与 OPD FLOPs。",
  computeMemory: "需同时做 student rollout 与 teacher logprob；奖励更稠密，但 teacher 服务成本不可忽略。",
  parallelism: "teacher scoring、student rollout 与 trainer 可拆分；适合异步服务式训练。",
  limitations: "teacher/student 分布差太大时 reverse KL 可能失效；博客 FLOPs 依赖实现和初始化，非通用倍率。",
  availability: "官方博客、伪代码与 Tinker 可复现实验 recipe 已公开。",
  breakthroughs: ["逐 token 稠密 on-policy 监督", "teacher logprob 直接形成 advantage", "兼顾蒸馏与 RL"],
  sources: [
    source("opd-blog", "On-Policy Distillation", "Thinking Machines Lab", "https://thinkingmachines.ai/blog/on-policy-distillation/", "官方博客"),
    source("opd-recipe", "Model Distillation Recipes", "Thinking Machines Lab", "https://tinker-docs.thinkingmachines.ai/cookbook/recipes/distillation/", "代码仓"),
  ],
});

const triton = technology({
  id: "tech-triton",
  date: "2019-06-22",
  title: "Triton",
  organization: "Harvard / OpenAI",
  category: "高效算子",
  eyebrow: "论文 + 代码仓 / GPU DSL",
  summary: "以 block/tile 为编程抽象，让开发者用 Python 风格 DSL 写自定义 GPU kernel，由编译器负责共享内存、合并访存与调度。",
  score: "MAPL 2019",
  tags: ["Triton", "GPU DSL", "Compiler", "Kernel"],
  situation: "CUDA kernel 性能依赖大量硬件细节，研究者难以快速实现新算子；高层框架又缺少足够控制。",
  target: "在比 CUDA 更高的生产力下，达到接近专家手写库的 GPU 性能。",
  action: "设计 tile-level IR、编译器与 autotuning；用 GEMM、卷积等工作负载对比 cuBLAS/cuDNN 和手写实现，随后以开源 Triton 1.0 产品化。",
  result: "论文与官方发布展示选定 GEMM/深度学习算子可达到专用库相当性能；结果是 workload-specific，不代表任意 kernel 自动最优。",
  mechanism: "程序实例处理张量 block；编译器做 dataflow analysis、内存合并、shared-memory allocation 与 GPU codegen。",
  bestFor: "融合算子、研究型新算子、PyTorch 自定义 kernel 与多后端编译实验。",
  experiment: "MAPL 2019 的矩阵乘/卷积等 microbenchmarks；OpenAI 发布页提供 softmax、matmul 示例。",
  computeMemory: "通过 fusion、tiling 与减少中间张量访问降低 launch/带宽开销。",
  parallelism: "单设备 kernel 内并行；可作为分布式训练框架的局部算子层。",
  limitations: "性能依赖 shape、数据类型和硬件；跨后端语义兼容不等于性能可移植。",
  availability: "Apache-2.0 开源，NVIDIA/AMD 生态成熟。",
  breakthroughs: ["tile-level GPU DSL", "编译器自动管理低层 GPU 细节", "Python 风格 kernel 开发"],
  sources: [
    source("triton-paper", "Triton: An Intermediate Language and Compiler for Tiled Neural Network Computations", "MAPL", "https://www.eecs.harvard.edu/~htk/publication/2019-mapl-tillet-kung-cox.pdf", "论文"),
    source("triton-repo", "Triton language and compiler", "Triton Project", "https://github.com/triton-lang/triton", "代码仓"),
    source("triton-blog", "Introducing Triton", "OpenAI", "https://openai.com/index/triton/", "官方博客"),
  ],
});

const ascendC = technology({
  id: "tech-ascend-c",
  date: "2023-05-06",
  title: "Ascend C",
  organization: "Huawei Ascend",
  category: "高效算子",
  eyebrow: "官方发布 / NPU Operator DSL",
  summary: "面向 Ascend AI Core 的 C/C++ 风格算子语言，以多级 API、自动并行与孪生调试降低手写 NPU 算子门槛。",
  score: "2 人月 → 2 人周",
  tags: ["Ascend C", "CANN", "NPU", "Operator"],
  situation: "高性能 Ascend 自定义算子需要理解 AI Core 存储层次、tiling、搬运与流水，开发周期长。",
  target: "用接近 C/C++ 的语言和分层 API 简化 NPU 算子开发，同时保留底层调优能力。",
  action: "提供 host tiling + device kernel 编程模型、多级算子 API、自动并行和 CPU/NPU 孪生调试；以约 300 行的大算子迁移案例评估开发周期。",
  result: "华为官方案例称约 300 行大算子开发周期由 2 人月降至 2 人周；这是开发效率案例，不是跨硬件运行性能 benchmark。",
  mechanism: "显式管理 Global Memory / Unified Buffer 与 AI Core 流水，host 侧决定 tiling，device 侧执行 kernel。",
  bestFor: "Ascend NPU 上需要硬件级控制的训练/推理自定义算子。",
  experiment: "官方发布与开发指南中的算子迁移/开发周期；没有统一 CUDA 对照性能。",
  computeMemory: "可显式控制数据搬运和片上 buffer；收益依具体算子 tiling。",
  parallelism: "AI Core 内核级并行；可被 CANN、MindSpore/PyTorch NPU 上层调用。",
  limitations: "绑定 Ascend/CANN 生态；官方公开材料缺少统一跨平台性能数字。",
  availability: "CANN 文档、样例与 Ascend C 开发工具可用。",
  breakthroughs: ["C/C++ 风格 NPU kernel", "host tiling + device kernel", "孪生调试"],
  sources: [
    source("ascend-c-release", "正式发布！昇腾 Ascend C 编程语言重磅来袭", "Huawei Ascend", "https://www.hiascend.com/developer/blog/details/0203119611291715080", "官方博客"),
    source("ascend-c-result", "昇腾 AI 基础软硬件全面升级", "Huawei", "https://e.huawei.com/cn/news/2023/branding/ascend-ai-basic-software", "官方博客"),
  ],
});

const ligerKernel = technology({
  id: "tech-liger-kernel",
  date: "2024-10-14",
  title: "Liger Kernel",
  organization: "LinkedIn",
  category: "高效算子",
  eyebrow: "论文 + 代码仓 / Training Kernels",
  summary: "把 RMSNorm、RoPE、SwiGLU、cross entropy 等 LLM 训练热点写成可直接替换的 Triton fusion/chunking kernel。",
  score: "+20% / −60%",
  tags: ["Liger", "Triton", "Fusion", "Training"],
  situation: "Hugging Face 训练中的逐算子实现产生大量中间张量与显存读写，限制吞吐、batch 和上下文长度。",
  target: "以低侵入 API 提供可复用、可验证收敛的高效训练 kernel。",
  action: "对 RMSNorm、RoPE、SwiGLU、CrossEntropy/FusedLinearCrossEntropy 等做 fusion 与 input chunking，并在多模型、多 GPU 训练环境与 HF baseline 比较。",
  result: "技术报告称热门 LLM 平均训练吞吐提高 20%、GPU 显存降低 60%；后训练 loss kernel 另有最高 80% 显存节省。",
  mechanism: "Triton fusion + chunking，避免完整 logits/中间激活物化和重复 HBM 往返。",
  bestFor: "Hugging Face 兼容 LLM 预训练、SFT、DPO/ORPO/CPO 等后训练。",
  experiment: "多种 LLM、GPU 与 FSDP/DeepSpeed 组合；同时做正确性、性能和收敛测试。",
  computeMemory: "平均 +20% throughput / −60% memory，具体收益依模型、shape 与被替换算子。",
  parallelism: "可与 FlashAttention、FSDP 和 DeepSpeed 组合。",
  limitations: "并非全模型编译器；不受支持的模型/shape 需手动集成，平均值不能当作单任务保证。",
  availability: "Apache-2.0 开源，PyPI 可安装，API 与 benchmark 公开。",
  breakthroughs: ["训练热点的 drop-in Triton kernels", "FusedLinearCrossEntropy", "兼容主流分布式框架"],
  sources: [
    source("liger-paper", "Liger Kernel: Efficient Triton Kernels for LLM Training", "LinkedIn", "https://arxiv.org/abs/2410.10989", "论文"),
    source("liger-repo", "Liger-Kernel", "LinkedIn", "https://github.com/linkedin/Liger-Kernel", "代码仓"),
  ],
});

const tritonAscend = technology({
  id: "tech-triton-ascend",
  date: "2025-05-29",
  title: "Triton-Ascend",
  organization: "Huawei Ascend / Triton Community",
  category: "高效算子",
  eyebrow: "代码仓 / Cross-Backend Compiler",
  summary: "把 Triton 核心语法与编译流程适配 Ascend NPU，并以独立算子库沉淀 NPU 特有的访存与调优模式。",
  score: "A2 / A3",
  tags: ["Triton-Ascend", "Ascend", "NPU", "Compiler"],
  situation: "CUDA/Triton kernel 无法原样在 Ascend 高效运行；芯片微架构、内存层次和编译部署机制不同。",
  target: "让 Triton 开发体验覆盖 Ascend，同时通过后端与算子级优化获得可用性能。",
  action: "实现 Ascend backend、参数/访存分析、编译和部署适配；另建 triton-ascend-ops 提供调优算子与迁移教程，覆盖 Atlas A2/A3。",
  result: "官方仓库已提供可运行框架、quick start 与调优算子库；尚无一份可引用的统一端到端训练加速百分比。",
  mechanism: "Triton DSL 前端 + Ascend 特定 compiler backend / runtime / operator tuning。",
  bestFor: "已有 Triton kernel 资产、希望迁移到 Ascend NPU 的算子团队。",
  experiment: "仓库中的单算子正确性/性能样例；需要在具体 A2/A3、CANN 版本上复测。",
  computeMemory: "目标是复用 fusion/tiling 表达；性能可移植性依算子逐项调优。",
  parallelism: "单 NPU kernel 层；可接入上层分布式训练栈。",
  limitations: "生态仍快速演进；语法兼容不保证同一 kernel 跨 GPU/NPU 性能相同。",
  availability: "Ascend 与 triton-lang 组织均有开源仓；调优算子库公开。",
  breakthroughs: ["Triton 语法跨到 Ascend", "NPU 专用编译后端", "迁移与调优算子库"],
  sources: [
    source("triton-ascend-repo", "Triton-Ascend", "Huawei Ascend", "https://github.com/Ascend/triton-ascend", "代码仓"),
    source("triton-ascend-ops", "Triton Ascend Ops", "Huawei Ascend", "https://github.com/Ascend/triton-ascend-ops", "代码仓"),
  ],
});

const megakernel = technology({
  id: "tech-megakernel",
  date: "2025-05-27",
  title: "LLM MegaKernel",
  organization: "Stanford Hazy Research",
  category: "高效算子",
  eyebrow: "官方博客 + 代码仓 / Whole-Model Fusion",
  summary: "把完整 Llama 前向过程融合进一个持久化 GPU kernel，消除跨层 kernel launch、同步与中间物化。",
  score: ">1.5×",
  tags: ["MegaKernel", "Fusion", "ThunderKittens", "Inference"],
  situation: "小 batch 低延迟推理时，数百次 kernel launch、层间同步与低 GPU 占用成为主导开销。",
  target: "跨越单算子 fusion 边界，把整个模型前向压进一个 kernel 以降低端到端延迟。",
  action: "以 ThunderKittens 构建 persistent megakernel，在 H100 上融合 Llama-1B 全部层，并与 vLLM/SGLang/编译基线比较。",
  result: "H100 上达到 78% memory bandwidth，端到端前向相对现有系统超过 1.5×；结果针对 Llama-1B BF16 低延迟推理。",
  mechanism: "persistent kernel + 跨层流水 + GPU 内全局调度，避免 kernel boundary。",
  bestFor: "固定模型/shape、batch 小、对单请求延迟极敏感的推理。",
  experiment: "Llama-1B BF16、NVIDIA H100；与 vLLM、SGLang 等端到端前向比较。",
  computeMemory: "减少 launch 与 HBM 中间往返；以更高 bandwidth utilization 换取手工调度复杂度。",
  parallelism: "单 GPU 内跨层并行/流水；多 GPU megakernel 仍需处理通信融合。",
  limitations: "高度模型与硬件特化；这里是推理结果，不是训练反向加速证明。",
  availability: "研究博客与 HazyResearch/Megakernels 代码仓公开。",
  breakthroughs: ["whole-model single kernel", "跨层流水与调度", "消除 kernel boundary"],
  sources: [
    source("megakernel-blog", "Look Ma, No Bubbles! Designing a Low-Latency Megakernel for Llama-1B", "Stanford Hazy Research", "https://hazyresearch.stanford.edu/blog/2025-05-27-no-bubbles", "官方博客"),
    source("megakernel-repo", "Megakernels", "Stanford Hazy Research", "https://github.com/HazyResearch/Megakernels", "代码仓"),
  ],
});

const megatron = technology({
  id: "tech-megatron-lm",
  date: "2019-09-17",
  title: "Megatron-LM / Tensor Parallel",
  organization: "NVIDIA",
  category: "并行方案",
  eyebrow: "论文 + 代码仓 / Model Parallel",
  summary: "在 Transformer 层内按矩阵列/行切分权重，用少量 collective 组合计算，奠定大模型 tensor parallel 基线。",
  score: "76% scaling",
  tags: ["Megatron-LM", "Tensor Parallel", "Model Parallel"],
  situation: "单 GPU 显存无法容纳数十亿参数，通用模型并行又需要复杂编译器或大量模型改造。",
  target: "用少量 PyTorch 通信操作实现高效、易组合的层内模型并行。",
  action: "按 Transformer MLP 与 attention 矩阵的列/行切分计算，结合数据并行；在 512 张 GPU 上训练 8.3B GPT/BERT 类模型。",
  result: "端到端持续 15.1 PFLOPS，相对单 GPU 达 76% scaling efficiency；8.3B 模型在 512 GPU 上收敛。",
  mechanism: "column-parallel + row-parallel linear，forward/backward 中插入 all-reduce/all-gather。",
  bestFor: "模型层本身无法装入单卡、节点内高速互联充足的大模型预训练。",
  experiment: "8.3B GPT 类模型，8-way model parallel × 64-way data parallel，512 GPU。",
  computeMemory: "分摊权重与 GEMM；通信量随 tensor-parallel 组与切分位置增长。",
  parallelism: "Tensor Parallel；现代 Megatron 进一步组合 PP/DP/EP/CP。",
  limitations: "跨慢网络做 TP 代价高；模型代码与 checkpoint 布局受切分影响。",
  availability: "论文与 NVIDIA/Megatron-LM 持续维护仓库公开。",
  breakthroughs: ["Transformer 层内张量切分", "少量 collective 完成模型并行", "与数据并行组合"],
  sources: [
    source("megatron-paper", "Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism", "NVIDIA", "https://arxiv.org/abs/1909.08053", "论文"),
    source("megatron-repo", "Megatron-LM", "NVIDIA", "https://github.com/NVIDIA/Megatron-LM", "代码仓"),
  ],
});

const zeroDeepSpeed = technology({
  id: "tech-deepspeed-zero",
  date: "2019-10-04",
  title: "DeepSpeed ZeRO",
  organization: "Microsoft Research",
  category: "并行方案",
  eyebrow: "论文 + 代码仓 / State Sharding",
  summary: "按阶段切分 optimizer state、gradient 和 parameter，消除数据并行中的状态复制，同时保留每层的大粒度计算。",
  score: "15 PFLOPS",
  tags: ["DeepSpeed", "ZeRO", "Shard", "Data Parallel"],
  situation: "传统数据并行每卡复制参数、梯度与优化器状态，模型规模受单卡显存限制；模型并行又增加使用复杂度。",
  target: "让可训练模型规模随设备数近线性增长，同时保持低通信量和数据并行使用方式。",
  action: "ZeRO Stage 1/2/3 逐步切分 optimizer/gradient/parameter，并在 400 GPU 上训练 40B/100B 级模型。",
  result: "超过 100B 参数训练达到 15 PFLOPS 和 super-linear speedup；论文分析可扩至 1T 参数，并称规模/性能较此前提高 8×/10×。",
  mechanism: "训练状态分片 + 需要时 all-gather 参数 / reduce-scatter 梯度。",
  bestFor: "希望以数据并行接口训练超出单卡显存的大模型；可叠加 TP/PP。",
  experiment: "最高 400 GPU，40B/100B 模型；分析 Stage 1–3 内存与通信。",
  computeMemory: "Stage 3 将参数、梯度、optimizer state 全分片；通信/显存可按 stage 权衡。",
  parallelism: "Sharded Data Parallel，可与 Tensor/Pipeline/Expert Parallel 组合。",
  limitations: "all-gather 调度、checkpoint 和 offload 会增加复杂度；实际吞吐依网络与分片粒度。",
  availability: "ZeRO 论文与 DeepSpeed 开源仓库可用。",
  breakthroughs: ["三阶段状态分片", "保留数据并行计算粒度", "可组合 CPU/NVMe offload"],
  sources: [
    source("zero-paper", "ZeRO: Memory Optimizations Toward Training Trillion Parameter Models", "Microsoft Research / SC", "https://arxiv.org/abs/1910.02054", "论文"),
    source("deepspeed-repo", "DeepSpeed", "Microsoft", "https://github.com/deepspeedai/DeepSpeed", "代码仓"),
  ],
});

const fsdp1 = technology({
  id: "tech-fsdp1",
  date: "2022-03-14",
  title: "PyTorch FSDP1",
  organization: "PyTorch / Meta",
  category: "并行方案",
  eyebrow: "官方博客 + 论文 / FlatParameter Sharding",
  summary: "把 ZeRO-3 式完整状态分片原生集成进 PyTorch，以 nested wrapping、FlatParameter 和通信/计算重叠降低迁移门槛。",
  score: "1T dense demo",
  tags: ["FSDP1", "PyTorch", "FlatParameter", "Full Shard"],
  situation: "ZeRO/FairScale 证明全分片有效，但 PyTorch 用户需要更原生、与 allocator/dispatcher 协同的工业实现。",
  target: "用接近本地模型的编程体验训练远超单卡容量的模型，并维持接近 DDP 的吞吐。",
  action: "按 module 把参数 flatten 后分片，前/反向按需 all-gather，完成后 reshard/free，并与 CUDA allocator、prefetch 和 CPU offload 联合设计。",
  result: "AWS scaling test 可训练 1T dense 模型；报告 GPT-1T 每 A100 84 TFLOPS、GPT-175B 每 A100 159 TFLOPS。论文显示接近 DDP 且 TFLOPS 近线性扩展。",
  mechanism: "FlatParameter group + nested FSDP wrapping + all-gather/reduce-scatter。",
  bestFor: "PyTorch 原生大模型训练，尤其模型状态超单卡容量但计算仍按数据并行执行。",
  experiment: "AWS A100 集群上的 GPT 175B/1T scaling；论文还覆盖不同硬件与配置。",
  computeMemory: "参数、梯度、optimizer state 全分片；临时 unsharded 参数峰值取决于 wrap 粒度/prefetch。",
  parallelism: "Fully Sharded Data Parallel，可与 TP 等组合但 FlatParameter 降低可组合性。",
  limitations: "flatten 后参数边界、冻结参数、state_dict 与其他 parallelism 组合复杂；内存调度较难预测。",
  availability: "PyTorch 原生稳定 API；官方已建议新项目考虑 FSDP2。",
  breakthroughs: ["PyTorch 原生 full sharding", "nested wrapping 控制峰值", "allocator-aware memory management"],
  sources: [
    source("fsdp1-blog", "Introducing PyTorch Fully Sharded Data Parallel API", "PyTorch", "https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/", "官方博客"),
    source("fsdp1-paper", "PyTorch FSDP: Experiences on Scaling Fully Sharded Data Parallel", "PyTorch / VLDB", "https://arxiv.org/abs/2304.11277", "论文"),
  ],
});

const fsdp2 = technology({
  id: "tech-fsdp2",
  date: "2024-07-24",
  title: "PyTorch FSDP2",
  organization: "PyTorch / Meta",
  category: "并行方案",
  eyebrow: "官方发布 / Per-Parameter DTensor",
  summary: "用 DTensor 的逐参数 dim-0 分片重写 FSDP，保留参数名与结构，改善可组合性、冻结参数、checkpoint 与显存可预测性。",
  score: "PyTorch 2.4 Prototype",
  tags: ["FSDP2", "DTensor", "Per-Parameter Sharding", "PyTorch"],
  situation: "FSDP1 的 FlatParameter 破坏原参数边界，使 tensor subclass、FP8、冻结参数、checkpoint 和多维并行组合困难。",
  target: "在维持相近吞吐的前提下，用逐参数分片获得更直观、可组合的表示。",
  action: "fully_shard 把参数原位转为 Shard(0) DTensor；module hooks 调度 all-gather/free/reduce-scatter，并重新设计多 stream 显存管理和显式 prefetch。",
  result: "官方文档定位为相对 FSDP1 保持相近 throughput；FSDP2 解除冻结参数约束、支持 communication-free sharded state dict，并带来确定性更强的显存行为。",
  mechanism: "per-parameter DTensor sharding + module-scoped communication groups。",
  bestFor: "需要 PyTorch 原生 composable distributed、FP8/tensor subclass、2D/3D 并行的新训练项目。",
  experiment: "PyTorch 2.4 prototype、TorchTitan 大模型训练；官方迁移文档以 FSDP1 对比功能/性能。",
  computeMemory: "全状态分片；避免 FSDP1 record_stream 模式，显存更可预测。",
  parallelism: "FSDP + DTensor DeviceMesh，便于组合 TP/PP/CP。",
  limitations: "无自动 bucketing，通信 grouping 由 module 结构决定；API 与 FSDP1 不兼容且需要迁移。",
  availability: "PyTorch 原生 fully_shard API 与迁移指南公开。",
  breakthroughs: ["逐参数 DTensor 分片", "保留 FQN/参数结构", "更强 composability 与 sharded checkpoint"],
  sources: [
    source("fsdp2-release", "PyTorch 2.4 Release Blog", "PyTorch", "https://pytorch.org/blog/pytorch2-4/", "官方博客"),
    source("fsdp2-docs", "torch.distributed.fsdp.fully_shard", "PyTorch", "https://docs.pytorch.org/docs/stable/distributed.fsdp.fully_shard.html", "代码仓"),
  ],
});

const deepEp = technology({
  id: "tech-deepep",
  date: "2025-02-17",
  title: "DeepEP / Expert Parallel Communication",
  organization: "DeepSeek-AI",
  category: "并行方案",
  eyebrow: "代码仓 / MoE All-to-All",
  summary: "面向 MoE dispatch/combine 的高吞吐与低延迟 GPU 通信库，联合 NVLink、RDMA、FP8 与计算通信重叠。",
  score: "up to 740 GB/s",
  tags: ["DeepEP", "MoE", "Expert Parallel", "RDMA", "NVLink"],
  situation: "专家并行要把 token 在 GPU/节点间 all-to-all dispatch/combine，通信与占用 SM 会吞噬稀疏 MoE 的计算收益。",
  target: "为训练高吞吐和推理低延迟提供专用通信 kernel，并尽量释放 SM 给 GEMM。",
  action: "实现 NVLink/RDMA dispatch-combine、FP8 dispatch/BF16 combine、hook-based compute overlap；按 DeepSeek-V3 的 8K token、7168 hidden、top-8 配置 benchmark。",
  result: "当前 V2 仓库表在 SM100 EP8 报告 726 GB/s dispatch、740 GB/s combine；相对 V1 最高 1.3× peak performance、最多节省 4× SM。",
  mechanism: "GPU-centric expert dispatch/combine kernels + NVLink/RDMA transport + buffer/layout 协同。",
  bestFor: "Hopper/Blackwell 集群上的大规模 sparse MoE 训练与推理。",
  experiment: "8K tokens/batch、hidden 7168、top-8、FP8 dispatch/BF16 combine；SM90/SM100、NVLink/CX7 RDMA。",
  computeMemory: "以专用 buffer 换高带宽与重叠；V2 buffer 占用高于 V1。",
  parallelism: "Expert Parallel 的通信层；需与 DP/TP/PP 训练框架组合。",
  limitations: "硬件与网络要求严格；仓库明确大规模结果暂未全部公开，逻辑带宽不能等同有效 payload 带宽。",
  availability: "MIT 开源；V2 依赖较新的 PyTorch/NCCL/CUDA 与 NVLink/RDMA。",
  breakthroughs: ["MoE 专用 dispatch/combine", "高吞吐与低延迟双路径", "细粒度计算通信重叠"],
  sources: [source("deepep-repo", "DeepEP", "DeepSeek-AI", "https://github.com/deepseek-ai/DeepEP", "代码仓")],
});

const veScaleFsdp = technology({
  id: "tech-vescale-fsdp",
  date: "2026-02-25",
  title: "veScale-FSDP",
  organization: "ByteDance",
  category: "并行方案",
  eyebrow: "论文 / Structure-Aware FSDP",
  summary: "以 RaggedShard 和结构感知 planner 让 FSDP 尊重 block quantization、Muon/Shampoo 等非逐元素结构，同时优化万卡通信与显存。",
  score: "+5–66% / −16–30%",
  tags: ["veScale-FSDP", "ByteDance", "RaggedShard", "Muon", "FSDP"],
  situation: "FSDP1/2 的固定逐元素或逐行分片与 block-wise 低精度、Muon/Shampoo 的矩阵结构冲突，在万卡规模也有通信/显存瓶颈。",
  target: "在兼容结构化训练方法的同时，超过现有 FSDP 的吞吐和显存效率并扩至数万 GPU。",
  action: "设计允许不等长、保留结构边界的 RaggedShard，以及 structure-aware planning；在多模型、优化器、量化与大规模集群上对比现有 FSDP。",
  result: "论文报告比现有 FSDP 系统高 5–66% 吞吐、低 16–30% 显存，并可扩展到数万 GPU。",
  mechanism: "flexible RaggedShard data placement + structure-aware sharding/communication planner。",
  bestFor: "block-wise quantized training、Muon/Shampoo 与超大规模集群训练。",
  experiment: "论文覆盖结构化 optimizer/量化与多规模训练；具体表格口径需随论文逐项阅读，不能把 66% 套到所有配置。",
  computeMemory: "报告 +5–66% throughput、−16–30% memory；收益来自布局、通信和峰值控制共同作用。",
  parallelism: "Fully Sharded Data Parallel，目标规模到 tens of thousands GPUs。",
  limitations: "截至 2026-07-19，论文结果可核验，但对应 veScale-FSDP 实现尚不能视为已公开可用；需等待代码与独立复现。",
  availability: "论文公开；现有 volcengine/veScale 仓库不等同论文所述 FSDP 实现。",
  breakthroughs: ["RaggedShard", "structure-aware planner", "原生支持 Muon/Shampoo 与 block quantization"],
  tier: "frontier",
  sources: [source("vescale-fsdp-paper", "veScale-FSDP: Flexible and High-Performance FSDP at Scale", "ByteDance", "https://arxiv.org/abs/2602.22437", "论文")],
});

export const trainingTechnologyLanes: TimelineLane[] = [
  {
    id: "training-tech-architecture",
    group: "训练技术 / 01",
    title: "模型结构 / 优化器",
    description: "Full/Paged/Linear Attention、MoE 负载均衡与 Muon",
    color: "cyan",
    events: [fullAttention, switchTransformer, expertChoice, pagedAttention, lossFreeBalancing, gatedDeltaNet, muon],
  },
  {
    id: "training-tech-algorithm",
    group: "训练技术 / 02",
    title: "算法流程 / Post-training",
    description: "GRPO、视觉生成 RL、DiffusionNFT 与 On-Policy Distillation",
    color: "violet",
    events: [grpo, danceGrpo, diffusionNft, opd],
  },
  {
    id: "training-tech-kernel",
    group: "训练技术 / 03",
    title: "高效算子 / 编译",
    description: "Triton、Ascend C、Liger、Triton-Ascend 与 MegaKernel",
    color: "green",
    events: [triton, ascendC, ligerKernel, tritonAscend, megakernel],
  },
  {
    id: "training-tech-parallel",
    group: "训练技术 / 04",
    title: "高效并行 / 通信",
    description: "Megatron、DeepSpeed、FSDP1/2、DeepEP 与 veScale-FSDP",
    color: "amber",
    events: [megatron, zeroDeepSpeed, fsdp1, fsdp2, deepEp, veScaleFsdp],
  },
];

export const trainingTechnologies = trainingTechnologyLanes.flatMap((lane) => lane.events);
